// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convolution,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=793,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=7107,HLS_SYN_LUT=9086,HLS_VERSION=2020_1}" *)

module convolution (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_In_ddr_AWVALID,
        m_axi_In_ddr_AWREADY,
        m_axi_In_ddr_AWADDR,
        m_axi_In_ddr_AWID,
        m_axi_In_ddr_AWLEN,
        m_axi_In_ddr_AWSIZE,
        m_axi_In_ddr_AWBURST,
        m_axi_In_ddr_AWLOCK,
        m_axi_In_ddr_AWCACHE,
        m_axi_In_ddr_AWPROT,
        m_axi_In_ddr_AWQOS,
        m_axi_In_ddr_AWREGION,
        m_axi_In_ddr_AWUSER,
        m_axi_In_ddr_WVALID,
        m_axi_In_ddr_WREADY,
        m_axi_In_ddr_WDATA,
        m_axi_In_ddr_WSTRB,
        m_axi_In_ddr_WLAST,
        m_axi_In_ddr_WID,
        m_axi_In_ddr_WUSER,
        m_axi_In_ddr_ARVALID,
        m_axi_In_ddr_ARREADY,
        m_axi_In_ddr_ARADDR,
        m_axi_In_ddr_ARID,
        m_axi_In_ddr_ARLEN,
        m_axi_In_ddr_ARSIZE,
        m_axi_In_ddr_ARBURST,
        m_axi_In_ddr_ARLOCK,
        m_axi_In_ddr_ARCACHE,
        m_axi_In_ddr_ARPROT,
        m_axi_In_ddr_ARQOS,
        m_axi_In_ddr_ARREGION,
        m_axi_In_ddr_ARUSER,
        m_axi_In_ddr_RVALID,
        m_axi_In_ddr_RREADY,
        m_axi_In_ddr_RDATA,
        m_axi_In_ddr_RLAST,
        m_axi_In_ddr_RID,
        m_axi_In_ddr_RUSER,
        m_axi_In_ddr_RRESP,
        m_axi_In_ddr_BVALID,
        m_axi_In_ddr_BREADY,
        m_axi_In_ddr_BRESP,
        m_axi_In_ddr_BID,
        m_axi_In_ddr_BUSER,
        m_axi_W_ddr_AWVALID,
        m_axi_W_ddr_AWREADY,
        m_axi_W_ddr_AWADDR,
        m_axi_W_ddr_AWID,
        m_axi_W_ddr_AWLEN,
        m_axi_W_ddr_AWSIZE,
        m_axi_W_ddr_AWBURST,
        m_axi_W_ddr_AWLOCK,
        m_axi_W_ddr_AWCACHE,
        m_axi_W_ddr_AWPROT,
        m_axi_W_ddr_AWQOS,
        m_axi_W_ddr_AWREGION,
        m_axi_W_ddr_AWUSER,
        m_axi_W_ddr_WVALID,
        m_axi_W_ddr_WREADY,
        m_axi_W_ddr_WDATA,
        m_axi_W_ddr_WSTRB,
        m_axi_W_ddr_WLAST,
        m_axi_W_ddr_WID,
        m_axi_W_ddr_WUSER,
        m_axi_W_ddr_ARVALID,
        m_axi_W_ddr_ARREADY,
        m_axi_W_ddr_ARADDR,
        m_axi_W_ddr_ARID,
        m_axi_W_ddr_ARLEN,
        m_axi_W_ddr_ARSIZE,
        m_axi_W_ddr_ARBURST,
        m_axi_W_ddr_ARLOCK,
        m_axi_W_ddr_ARCACHE,
        m_axi_W_ddr_ARPROT,
        m_axi_W_ddr_ARQOS,
        m_axi_W_ddr_ARREGION,
        m_axi_W_ddr_ARUSER,
        m_axi_W_ddr_RVALID,
        m_axi_W_ddr_RREADY,
        m_axi_W_ddr_RDATA,
        m_axi_W_ddr_RLAST,
        m_axi_W_ddr_RID,
        m_axi_W_ddr_RUSER,
        m_axi_W_ddr_RRESP,
        m_axi_W_ddr_BVALID,
        m_axi_W_ddr_BREADY,
        m_axi_W_ddr_BRESP,
        m_axi_W_ddr_BID,
        m_axi_W_ddr_BUSER,
        m_axi_Out_ddr_AWVALID,
        m_axi_Out_ddr_AWREADY,
        m_axi_Out_ddr_AWADDR,
        m_axi_Out_ddr_AWID,
        m_axi_Out_ddr_AWLEN,
        m_axi_Out_ddr_AWSIZE,
        m_axi_Out_ddr_AWBURST,
        m_axi_Out_ddr_AWLOCK,
        m_axi_Out_ddr_AWCACHE,
        m_axi_Out_ddr_AWPROT,
        m_axi_Out_ddr_AWQOS,
        m_axi_Out_ddr_AWREGION,
        m_axi_Out_ddr_AWUSER,
        m_axi_Out_ddr_WVALID,
        m_axi_Out_ddr_WREADY,
        m_axi_Out_ddr_WDATA,
        m_axi_Out_ddr_WSTRB,
        m_axi_Out_ddr_WLAST,
        m_axi_Out_ddr_WID,
        m_axi_Out_ddr_WUSER,
        m_axi_Out_ddr_ARVALID,
        m_axi_Out_ddr_ARREADY,
        m_axi_Out_ddr_ARADDR,
        m_axi_Out_ddr_ARID,
        m_axi_Out_ddr_ARLEN,
        m_axi_Out_ddr_ARSIZE,
        m_axi_Out_ddr_ARBURST,
        m_axi_Out_ddr_ARLOCK,
        m_axi_Out_ddr_ARCACHE,
        m_axi_Out_ddr_ARPROT,
        m_axi_Out_ddr_ARQOS,
        m_axi_Out_ddr_ARREGION,
        m_axi_Out_ddr_ARUSER,
        m_axi_Out_ddr_RVALID,
        m_axi_Out_ddr_RREADY,
        m_axi_Out_ddr_RDATA,
        m_axi_Out_ddr_RLAST,
        m_axi_Out_ddr_RID,
        m_axi_Out_ddr_RUSER,
        m_axi_Out_ddr_RRESP,
        m_axi_Out_ddr_BVALID,
        m_axi_Out_ddr_BREADY,
        m_axi_Out_ddr_BRESP,
        m_axi_Out_ddr_BID,
        m_axi_Out_ddr_BUSER
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_M_AXI_IN_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_IN_DDR_DATA_WIDTH = 32;
parameter    C_M_AXI_IN_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_IN_DDR_TARGET_ADDR = 0;
parameter    C_M_AXI_IN_DDR_USER_VALUE = 0;
parameter    C_M_AXI_IN_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_IN_DDR_CACHE_VALUE = 3;
parameter    C_M_AXI_W_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_W_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_W_DDR_DATA_WIDTH = 32;
parameter    C_M_AXI_W_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_W_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_W_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_W_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_W_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_W_DDR_TARGET_ADDR = 0;
parameter    C_M_AXI_W_DDR_USER_VALUE = 0;
parameter    C_M_AXI_W_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_W_DDR_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_OUT_DDR_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_DDR_TARGET_ADDR = 0;
parameter    C_M_AXI_OUT_DDR_USER_VALUE = 0;
parameter    C_M_AXI_OUT_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_OUT_DDR_CACHE_VALUE = 3;

parameter C_M_AXI_IN_DDR_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_W_DDR_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUT_DDR_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_In_ddr_AWVALID;
input   m_axi_In_ddr_AWREADY;
output  [C_M_AXI_IN_DDR_ADDR_WIDTH - 1:0] m_axi_In_ddr_AWADDR;
output  [C_M_AXI_IN_DDR_ID_WIDTH - 1:0] m_axi_In_ddr_AWID;
output  [7:0] m_axi_In_ddr_AWLEN;
output  [2:0] m_axi_In_ddr_AWSIZE;
output  [1:0] m_axi_In_ddr_AWBURST;
output  [1:0] m_axi_In_ddr_AWLOCK;
output  [3:0] m_axi_In_ddr_AWCACHE;
output  [2:0] m_axi_In_ddr_AWPROT;
output  [3:0] m_axi_In_ddr_AWQOS;
output  [3:0] m_axi_In_ddr_AWREGION;
output  [C_M_AXI_IN_DDR_AWUSER_WIDTH - 1:0] m_axi_In_ddr_AWUSER;
output   m_axi_In_ddr_WVALID;
input   m_axi_In_ddr_WREADY;
output  [C_M_AXI_IN_DDR_DATA_WIDTH - 1:0] m_axi_In_ddr_WDATA;
output  [C_M_AXI_IN_DDR_WSTRB_WIDTH - 1:0] m_axi_In_ddr_WSTRB;
output   m_axi_In_ddr_WLAST;
output  [C_M_AXI_IN_DDR_ID_WIDTH - 1:0] m_axi_In_ddr_WID;
output  [C_M_AXI_IN_DDR_WUSER_WIDTH - 1:0] m_axi_In_ddr_WUSER;
output   m_axi_In_ddr_ARVALID;
input   m_axi_In_ddr_ARREADY;
output  [C_M_AXI_IN_DDR_ADDR_WIDTH - 1:0] m_axi_In_ddr_ARADDR;
output  [C_M_AXI_IN_DDR_ID_WIDTH - 1:0] m_axi_In_ddr_ARID;
output  [7:0] m_axi_In_ddr_ARLEN;
output  [2:0] m_axi_In_ddr_ARSIZE;
output  [1:0] m_axi_In_ddr_ARBURST;
output  [1:0] m_axi_In_ddr_ARLOCK;
output  [3:0] m_axi_In_ddr_ARCACHE;
output  [2:0] m_axi_In_ddr_ARPROT;
output  [3:0] m_axi_In_ddr_ARQOS;
output  [3:0] m_axi_In_ddr_ARREGION;
output  [C_M_AXI_IN_DDR_ARUSER_WIDTH - 1:0] m_axi_In_ddr_ARUSER;
input   m_axi_In_ddr_RVALID;
output   m_axi_In_ddr_RREADY;
input  [C_M_AXI_IN_DDR_DATA_WIDTH - 1:0] m_axi_In_ddr_RDATA;
input   m_axi_In_ddr_RLAST;
input  [C_M_AXI_IN_DDR_ID_WIDTH - 1:0] m_axi_In_ddr_RID;
input  [C_M_AXI_IN_DDR_RUSER_WIDTH - 1:0] m_axi_In_ddr_RUSER;
input  [1:0] m_axi_In_ddr_RRESP;
input   m_axi_In_ddr_BVALID;
output   m_axi_In_ddr_BREADY;
input  [1:0] m_axi_In_ddr_BRESP;
input  [C_M_AXI_IN_DDR_ID_WIDTH - 1:0] m_axi_In_ddr_BID;
input  [C_M_AXI_IN_DDR_BUSER_WIDTH - 1:0] m_axi_In_ddr_BUSER;
output   m_axi_W_ddr_AWVALID;
input   m_axi_W_ddr_AWREADY;
output  [C_M_AXI_W_DDR_ADDR_WIDTH - 1:0] m_axi_W_ddr_AWADDR;
output  [C_M_AXI_W_DDR_ID_WIDTH - 1:0] m_axi_W_ddr_AWID;
output  [7:0] m_axi_W_ddr_AWLEN;
output  [2:0] m_axi_W_ddr_AWSIZE;
output  [1:0] m_axi_W_ddr_AWBURST;
output  [1:0] m_axi_W_ddr_AWLOCK;
output  [3:0] m_axi_W_ddr_AWCACHE;
output  [2:0] m_axi_W_ddr_AWPROT;
output  [3:0] m_axi_W_ddr_AWQOS;
output  [3:0] m_axi_W_ddr_AWREGION;
output  [C_M_AXI_W_DDR_AWUSER_WIDTH - 1:0] m_axi_W_ddr_AWUSER;
output   m_axi_W_ddr_WVALID;
input   m_axi_W_ddr_WREADY;
output  [C_M_AXI_W_DDR_DATA_WIDTH - 1:0] m_axi_W_ddr_WDATA;
output  [C_M_AXI_W_DDR_WSTRB_WIDTH - 1:0] m_axi_W_ddr_WSTRB;
output   m_axi_W_ddr_WLAST;
output  [C_M_AXI_W_DDR_ID_WIDTH - 1:0] m_axi_W_ddr_WID;
output  [C_M_AXI_W_DDR_WUSER_WIDTH - 1:0] m_axi_W_ddr_WUSER;
output   m_axi_W_ddr_ARVALID;
input   m_axi_W_ddr_ARREADY;
output  [C_M_AXI_W_DDR_ADDR_WIDTH - 1:0] m_axi_W_ddr_ARADDR;
output  [C_M_AXI_W_DDR_ID_WIDTH - 1:0] m_axi_W_ddr_ARID;
output  [7:0] m_axi_W_ddr_ARLEN;
output  [2:0] m_axi_W_ddr_ARSIZE;
output  [1:0] m_axi_W_ddr_ARBURST;
output  [1:0] m_axi_W_ddr_ARLOCK;
output  [3:0] m_axi_W_ddr_ARCACHE;
output  [2:0] m_axi_W_ddr_ARPROT;
output  [3:0] m_axi_W_ddr_ARQOS;
output  [3:0] m_axi_W_ddr_ARREGION;
output  [C_M_AXI_W_DDR_ARUSER_WIDTH - 1:0] m_axi_W_ddr_ARUSER;
input   m_axi_W_ddr_RVALID;
output   m_axi_W_ddr_RREADY;
input  [C_M_AXI_W_DDR_DATA_WIDTH - 1:0] m_axi_W_ddr_RDATA;
input   m_axi_W_ddr_RLAST;
input  [C_M_AXI_W_DDR_ID_WIDTH - 1:0] m_axi_W_ddr_RID;
input  [C_M_AXI_W_DDR_RUSER_WIDTH - 1:0] m_axi_W_ddr_RUSER;
input  [1:0] m_axi_W_ddr_RRESP;
input   m_axi_W_ddr_BVALID;
output   m_axi_W_ddr_BREADY;
input  [1:0] m_axi_W_ddr_BRESP;
input  [C_M_AXI_W_DDR_ID_WIDTH - 1:0] m_axi_W_ddr_BID;
input  [C_M_AXI_W_DDR_BUSER_WIDTH - 1:0] m_axi_W_ddr_BUSER;
output   m_axi_Out_ddr_AWVALID;
input   m_axi_Out_ddr_AWREADY;
output  [C_M_AXI_OUT_DDR_ADDR_WIDTH - 1:0] m_axi_Out_ddr_AWADDR;
output  [C_M_AXI_OUT_DDR_ID_WIDTH - 1:0] m_axi_Out_ddr_AWID;
output  [7:0] m_axi_Out_ddr_AWLEN;
output  [2:0] m_axi_Out_ddr_AWSIZE;
output  [1:0] m_axi_Out_ddr_AWBURST;
output  [1:0] m_axi_Out_ddr_AWLOCK;
output  [3:0] m_axi_Out_ddr_AWCACHE;
output  [2:0] m_axi_Out_ddr_AWPROT;
output  [3:0] m_axi_Out_ddr_AWQOS;
output  [3:0] m_axi_Out_ddr_AWREGION;
output  [C_M_AXI_OUT_DDR_AWUSER_WIDTH - 1:0] m_axi_Out_ddr_AWUSER;
output   m_axi_Out_ddr_WVALID;
input   m_axi_Out_ddr_WREADY;
output  [C_M_AXI_OUT_DDR_DATA_WIDTH - 1:0] m_axi_Out_ddr_WDATA;
output  [C_M_AXI_OUT_DDR_WSTRB_WIDTH - 1:0] m_axi_Out_ddr_WSTRB;
output   m_axi_Out_ddr_WLAST;
output  [C_M_AXI_OUT_DDR_ID_WIDTH - 1:0] m_axi_Out_ddr_WID;
output  [C_M_AXI_OUT_DDR_WUSER_WIDTH - 1:0] m_axi_Out_ddr_WUSER;
output   m_axi_Out_ddr_ARVALID;
input   m_axi_Out_ddr_ARREADY;
output  [C_M_AXI_OUT_DDR_ADDR_WIDTH - 1:0] m_axi_Out_ddr_ARADDR;
output  [C_M_AXI_OUT_DDR_ID_WIDTH - 1:0] m_axi_Out_ddr_ARID;
output  [7:0] m_axi_Out_ddr_ARLEN;
output  [2:0] m_axi_Out_ddr_ARSIZE;
output  [1:0] m_axi_Out_ddr_ARBURST;
output  [1:0] m_axi_Out_ddr_ARLOCK;
output  [3:0] m_axi_Out_ddr_ARCACHE;
output  [2:0] m_axi_Out_ddr_ARPROT;
output  [3:0] m_axi_Out_ddr_ARQOS;
output  [3:0] m_axi_Out_ddr_ARREGION;
output  [C_M_AXI_OUT_DDR_ARUSER_WIDTH - 1:0] m_axi_Out_ddr_ARUSER;
input   m_axi_Out_ddr_RVALID;
output   m_axi_Out_ddr_RREADY;
input  [C_M_AXI_OUT_DDR_DATA_WIDTH - 1:0] m_axi_Out_ddr_RDATA;
input   m_axi_Out_ddr_RLAST;
input  [C_M_AXI_OUT_DDR_ID_WIDTH - 1:0] m_axi_Out_ddr_RID;
input  [C_M_AXI_OUT_DDR_RUSER_WIDTH - 1:0] m_axi_Out_ddr_RUSER;
input  [1:0] m_axi_Out_ddr_RRESP;
input   m_axi_Out_ddr_BVALID;
output   m_axi_Out_ddr_BREADY;
input  [1:0] m_axi_Out_ddr_BRESP;
input  [C_M_AXI_OUT_DDR_ID_WIDTH - 1:0] m_axi_Out_ddr_BID;
input  [C_M_AXI_OUT_DDR_BUSER_WIDTH - 1:0] m_axi_Out_ddr_BUSER;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    W_ddr_AWREADY;
wire    W_ddr_WREADY;
reg    W_ddr_ARVALID;
wire    W_ddr_ARREADY;
wire    W_ddr_RVALID;
reg    W_ddr_RREADY;
wire   [31:0] W_ddr_RDATA;
wire    W_ddr_RLAST;
wire   [0:0] W_ddr_RID;
wire   [0:0] W_ddr_RUSER;
wire   [1:0] W_ddr_RRESP;
wire    W_ddr_BVALID;
wire   [1:0] W_ddr_BRESP;
wire   [0:0] W_ddr_BID;
wire   [0:0] W_ddr_BUSER;
reg    Out_ddr_AWVALID;
wire    Out_ddr_AWREADY;
reg    Out_ddr_WVALID;
wire    Out_ddr_WREADY;
wire    Out_ddr_ARREADY;
wire    Out_ddr_RVALID;
wire   [31:0] Out_ddr_RDATA;
wire    Out_ddr_RLAST;
wire   [0:0] Out_ddr_RID;
wire   [0:0] Out_ddr_RUSER;
wire   [1:0] Out_ddr_RRESP;
wire    Out_ddr_BVALID;
reg    Out_ddr_BREADY;
wire   [1:0] Out_ddr_BRESP;
wire   [0:0] Out_ddr_BID;
wire   [0:0] Out_ddr_BUSER;
wire   [31:0] Out_0_0_q0;
wire   [31:0] Out_0_1_q0;
wire   [31:0] Out_0_2_q0;
wire   [31:0] Out_0_3_q0;
wire   [31:0] Out_0_4_q0;
wire   [31:0] Out_0_5_q0;
wire   [31:0] Out_0_6_q0;
wire   [31:0] Out_0_7_q0;
wire   [31:0] Out_0_8_q0;
wire   [31:0] Out_0_9_q0;
wire   [31:0] Out_0_10_q0;
wire   [31:0] Out_0_11_q0;
wire   [31:0] Out_0_12_q0;
wire   [31:0] Out_0_13_q0;
wire   [31:0] Out_1_0_q0;
wire   [31:0] Out_1_1_q0;
wire   [31:0] Out_1_2_q0;
wire   [31:0] Out_1_3_q0;
wire   [31:0] Out_1_4_q0;
wire   [31:0] Out_1_5_q0;
wire   [31:0] Out_1_6_q0;
wire   [31:0] Out_1_7_q0;
wire   [31:0] Out_1_8_q0;
wire   [31:0] Out_1_9_q0;
wire   [31:0] Out_1_10_q0;
wire   [31:0] Out_1_11_q0;
wire   [31:0] Out_1_12_q0;
wire   [31:0] Out_1_13_q0;
wire   [31:0] Out_2_0_q0;
wire   [31:0] Out_2_1_q0;
wire   [31:0] Out_2_2_q0;
wire   [31:0] Out_2_3_q0;
wire   [31:0] Out_2_4_q0;
wire   [31:0] Out_2_5_q0;
wire   [31:0] Out_2_6_q0;
wire   [31:0] Out_2_7_q0;
wire   [31:0] Out_2_8_q0;
wire   [31:0] Out_2_9_q0;
wire   [31:0] Out_2_10_q0;
wire   [31:0] Out_2_11_q0;
wire   [31:0] Out_2_12_q0;
wire   [31:0] Out_2_13_q0;
wire   [31:0] Out_3_0_q0;
wire   [31:0] Out_3_1_q0;
wire   [31:0] Out_3_2_q0;
wire   [31:0] Out_3_3_q0;
wire   [31:0] Out_3_4_q0;
wire   [31:0] Out_3_5_q0;
wire   [31:0] Out_3_6_q0;
wire   [31:0] Out_3_7_q0;
wire   [31:0] Out_3_8_q0;
wire   [31:0] Out_3_9_q0;
wire   [31:0] Out_3_10_q0;
wire   [31:0] Out_3_11_q0;
wire   [31:0] Out_3_12_q0;
wire   [31:0] Out_3_13_q0;
wire    grp_Process_r_fu_254_ap_start;
wire    grp_Process_r_fu_254_ap_done;
wire    grp_Process_r_fu_254_ap_idle;
wire    grp_Process_r_fu_254_ap_ready;
wire    grp_Process_r_fu_254_m_axi_W_ddr_AWVALID;
wire   [31:0] grp_Process_r_fu_254_m_axi_W_ddr_AWADDR;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_AWID;
wire   [31:0] grp_Process_r_fu_254_m_axi_W_ddr_AWLEN;
wire   [2:0] grp_Process_r_fu_254_m_axi_W_ddr_AWSIZE;
wire   [1:0] grp_Process_r_fu_254_m_axi_W_ddr_AWBURST;
wire   [1:0] grp_Process_r_fu_254_m_axi_W_ddr_AWLOCK;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_AWCACHE;
wire   [2:0] grp_Process_r_fu_254_m_axi_W_ddr_AWPROT;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_AWQOS;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_AWREGION;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_AWUSER;
wire    grp_Process_r_fu_254_m_axi_W_ddr_WVALID;
wire   [31:0] grp_Process_r_fu_254_m_axi_W_ddr_WDATA;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_WSTRB;
wire    grp_Process_r_fu_254_m_axi_W_ddr_WLAST;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_WID;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_WUSER;
wire    grp_Process_r_fu_254_m_axi_W_ddr_ARVALID;
wire   [31:0] grp_Process_r_fu_254_m_axi_W_ddr_ARADDR;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_ARID;
wire   [31:0] grp_Process_r_fu_254_m_axi_W_ddr_ARLEN;
wire   [2:0] grp_Process_r_fu_254_m_axi_W_ddr_ARSIZE;
wire   [1:0] grp_Process_r_fu_254_m_axi_W_ddr_ARBURST;
wire   [1:0] grp_Process_r_fu_254_m_axi_W_ddr_ARLOCK;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_ARCACHE;
wire   [2:0] grp_Process_r_fu_254_m_axi_W_ddr_ARPROT;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_ARQOS;
wire   [3:0] grp_Process_r_fu_254_m_axi_W_ddr_ARREGION;
wire   [0:0] grp_Process_r_fu_254_m_axi_W_ddr_ARUSER;
wire    grp_Process_r_fu_254_m_axi_W_ddr_RREADY;
wire    grp_Process_r_fu_254_m_axi_W_ddr_BREADY;
wire    grp_Offload_Out_fu_260_ap_start;
wire    grp_Offload_Out_fu_260_ap_done;
wire    grp_Offload_Out_fu_260_ap_idle;
wire    grp_Offload_Out_fu_260_ap_ready;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_AWVALID;
wire   [31:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWADDR;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWID;
wire   [31:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLEN;
wire   [2:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWSIZE;
wire   [1:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWBURST;
wire   [1:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLOCK;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWCACHE;
wire   [2:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWPROT;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWQOS;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWREGION;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_AWUSER;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_WVALID;
wire   [31:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_WDATA;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_WSTRB;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_WLAST;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_WID;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_WUSER;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_ARVALID;
wire   [31:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARADDR;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARID;
wire   [31:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARLEN;
wire   [2:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARSIZE;
wire   [1:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARBURST;
wire   [1:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARLOCK;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARCACHE;
wire   [2:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARPROT;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARQOS;
wire   [3:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARREGION;
wire   [0:0] grp_Offload_Out_fu_260_m_axi_Out_ddr_ARUSER;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_RREADY;
wire    grp_Offload_Out_fu_260_m_axi_Out_ddr_BREADY;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_0_address0;
wire    grp_Offload_Out_fu_260_Out_0_0_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_1_address0;
wire    grp_Offload_Out_fu_260_Out_0_1_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_2_address0;
wire    grp_Offload_Out_fu_260_Out_0_2_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_3_address0;
wire    grp_Offload_Out_fu_260_Out_0_3_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_4_address0;
wire    grp_Offload_Out_fu_260_Out_0_4_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_5_address0;
wire    grp_Offload_Out_fu_260_Out_0_5_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_6_address0;
wire    grp_Offload_Out_fu_260_Out_0_6_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_7_address0;
wire    grp_Offload_Out_fu_260_Out_0_7_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_8_address0;
wire    grp_Offload_Out_fu_260_Out_0_8_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_9_address0;
wire    grp_Offload_Out_fu_260_Out_0_9_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_10_address0;
wire    grp_Offload_Out_fu_260_Out_0_10_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_11_address0;
wire    grp_Offload_Out_fu_260_Out_0_11_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_12_address0;
wire    grp_Offload_Out_fu_260_Out_0_12_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_0_13_address0;
wire    grp_Offload_Out_fu_260_Out_0_13_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_0_address0;
wire    grp_Offload_Out_fu_260_Out_1_0_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_1_address0;
wire    grp_Offload_Out_fu_260_Out_1_1_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_2_address0;
wire    grp_Offload_Out_fu_260_Out_1_2_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_3_address0;
wire    grp_Offload_Out_fu_260_Out_1_3_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_4_address0;
wire    grp_Offload_Out_fu_260_Out_1_4_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_5_address0;
wire    grp_Offload_Out_fu_260_Out_1_5_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_6_address0;
wire    grp_Offload_Out_fu_260_Out_1_6_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_7_address0;
wire    grp_Offload_Out_fu_260_Out_1_7_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_8_address0;
wire    grp_Offload_Out_fu_260_Out_1_8_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_9_address0;
wire    grp_Offload_Out_fu_260_Out_1_9_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_10_address0;
wire    grp_Offload_Out_fu_260_Out_1_10_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_11_address0;
wire    grp_Offload_Out_fu_260_Out_1_11_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_12_address0;
wire    grp_Offload_Out_fu_260_Out_1_12_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_1_13_address0;
wire    grp_Offload_Out_fu_260_Out_1_13_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_0_address0;
wire    grp_Offload_Out_fu_260_Out_2_0_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_1_address0;
wire    grp_Offload_Out_fu_260_Out_2_1_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_2_address0;
wire    grp_Offload_Out_fu_260_Out_2_2_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_3_address0;
wire    grp_Offload_Out_fu_260_Out_2_3_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_4_address0;
wire    grp_Offload_Out_fu_260_Out_2_4_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_5_address0;
wire    grp_Offload_Out_fu_260_Out_2_5_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_6_address0;
wire    grp_Offload_Out_fu_260_Out_2_6_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_7_address0;
wire    grp_Offload_Out_fu_260_Out_2_7_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_8_address0;
wire    grp_Offload_Out_fu_260_Out_2_8_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_9_address0;
wire    grp_Offload_Out_fu_260_Out_2_9_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_10_address0;
wire    grp_Offload_Out_fu_260_Out_2_10_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_11_address0;
wire    grp_Offload_Out_fu_260_Out_2_11_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_12_address0;
wire    grp_Offload_Out_fu_260_Out_2_12_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_2_13_address0;
wire    grp_Offload_Out_fu_260_Out_2_13_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_0_address0;
wire    grp_Offload_Out_fu_260_Out_3_0_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_1_address0;
wire    grp_Offload_Out_fu_260_Out_3_1_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_2_address0;
wire    grp_Offload_Out_fu_260_Out_3_2_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_3_address0;
wire    grp_Offload_Out_fu_260_Out_3_3_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_4_address0;
wire    grp_Offload_Out_fu_260_Out_3_4_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_5_address0;
wire    grp_Offload_Out_fu_260_Out_3_5_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_6_address0;
wire    grp_Offload_Out_fu_260_Out_3_6_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_7_address0;
wire    grp_Offload_Out_fu_260_Out_3_7_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_8_address0;
wire    grp_Offload_Out_fu_260_Out_3_8_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_9_address0;
wire    grp_Offload_Out_fu_260_Out_3_9_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_10_address0;
wire    grp_Offload_Out_fu_260_Out_3_10_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_11_address0;
wire    grp_Offload_Out_fu_260_Out_3_11_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_12_address0;
wire    grp_Offload_Out_fu_260_Out_3_12_ce0;
wire   [3:0] grp_Offload_Out_fu_260_Out_3_13_address0;
wire    grp_Offload_Out_fu_260_Out_3_13_ce0;
reg    grp_Process_r_fu_254_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Offload_Out_fu_260_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_Process_r_fu_254_ap_start_reg = 1'b0;
#0 grp_Offload_Out_fu_260_ap_start_reg = 1'b0;
end

convolution_W_ddr_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_W_DDR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_W_DDR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_W_DDR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_W_DDR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_W_DDR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_W_DDR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_W_DDR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_W_DDR_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_W_DDR_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_W_DDR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_W_DDR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_W_DDR_CACHE_VALUE ))
convolution_W_ddr_m_axi_U(
    .AWVALID(m_axi_W_ddr_AWVALID),
    .AWREADY(m_axi_W_ddr_AWREADY),
    .AWADDR(m_axi_W_ddr_AWADDR),
    .AWID(m_axi_W_ddr_AWID),
    .AWLEN(m_axi_W_ddr_AWLEN),
    .AWSIZE(m_axi_W_ddr_AWSIZE),
    .AWBURST(m_axi_W_ddr_AWBURST),
    .AWLOCK(m_axi_W_ddr_AWLOCK),
    .AWCACHE(m_axi_W_ddr_AWCACHE),
    .AWPROT(m_axi_W_ddr_AWPROT),
    .AWQOS(m_axi_W_ddr_AWQOS),
    .AWREGION(m_axi_W_ddr_AWREGION),
    .AWUSER(m_axi_W_ddr_AWUSER),
    .WVALID(m_axi_W_ddr_WVALID),
    .WREADY(m_axi_W_ddr_WREADY),
    .WDATA(m_axi_W_ddr_WDATA),
    .WSTRB(m_axi_W_ddr_WSTRB),
    .WLAST(m_axi_W_ddr_WLAST),
    .WID(m_axi_W_ddr_WID),
    .WUSER(m_axi_W_ddr_WUSER),
    .ARVALID(m_axi_W_ddr_ARVALID),
    .ARREADY(m_axi_W_ddr_ARREADY),
    .ARADDR(m_axi_W_ddr_ARADDR),
    .ARID(m_axi_W_ddr_ARID),
    .ARLEN(m_axi_W_ddr_ARLEN),
    .ARSIZE(m_axi_W_ddr_ARSIZE),
    .ARBURST(m_axi_W_ddr_ARBURST),
    .ARLOCK(m_axi_W_ddr_ARLOCK),
    .ARCACHE(m_axi_W_ddr_ARCACHE),
    .ARPROT(m_axi_W_ddr_ARPROT),
    .ARQOS(m_axi_W_ddr_ARQOS),
    .ARREGION(m_axi_W_ddr_ARREGION),
    .ARUSER(m_axi_W_ddr_ARUSER),
    .RVALID(m_axi_W_ddr_RVALID),
    .RREADY(m_axi_W_ddr_RREADY),
    .RDATA(m_axi_W_ddr_RDATA),
    .RLAST(m_axi_W_ddr_RLAST),
    .RID(m_axi_W_ddr_RID),
    .RUSER(m_axi_W_ddr_RUSER),
    .RRESP(m_axi_W_ddr_RRESP),
    .BVALID(m_axi_W_ddr_BVALID),
    .BREADY(m_axi_W_ddr_BREADY),
    .BRESP(m_axi_W_ddr_BRESP),
    .BID(m_axi_W_ddr_BID),
    .BUSER(m_axi_W_ddr_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(W_ddr_ARVALID),
    .I_ARREADY(W_ddr_ARREADY),
    .I_ARADDR(grp_Process_r_fu_254_m_axi_W_ddr_ARADDR),
    .I_ARID(grp_Process_r_fu_254_m_axi_W_ddr_ARID),
    .I_ARLEN(grp_Process_r_fu_254_m_axi_W_ddr_ARLEN),
    .I_ARSIZE(grp_Process_r_fu_254_m_axi_W_ddr_ARSIZE),
    .I_ARLOCK(grp_Process_r_fu_254_m_axi_W_ddr_ARLOCK),
    .I_ARCACHE(grp_Process_r_fu_254_m_axi_W_ddr_ARCACHE),
    .I_ARQOS(grp_Process_r_fu_254_m_axi_W_ddr_ARQOS),
    .I_ARPROT(grp_Process_r_fu_254_m_axi_W_ddr_ARPROT),
    .I_ARUSER(grp_Process_r_fu_254_m_axi_W_ddr_ARUSER),
    .I_ARBURST(grp_Process_r_fu_254_m_axi_W_ddr_ARBURST),
    .I_ARREGION(grp_Process_r_fu_254_m_axi_W_ddr_ARREGION),
    .I_RVALID(W_ddr_RVALID),
    .I_RREADY(W_ddr_RREADY),
    .I_RDATA(W_ddr_RDATA),
    .I_RID(W_ddr_RID),
    .I_RUSER(W_ddr_RUSER),
    .I_RRESP(W_ddr_RRESP),
    .I_RLAST(W_ddr_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(W_ddr_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(W_ddr_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(W_ddr_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(W_ddr_BRESP),
    .I_BID(W_ddr_BID),
    .I_BUSER(W_ddr_BUSER)
);

convolution_Out_ddr_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUT_DDR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUT_DDR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUT_DDR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUT_DDR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUT_DDR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUT_DDR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUT_DDR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUT_DDR_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_OUT_DDR_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_OUT_DDR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUT_DDR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUT_DDR_CACHE_VALUE ))
convolution_Out_ddr_m_axi_U(
    .AWVALID(m_axi_Out_ddr_AWVALID),
    .AWREADY(m_axi_Out_ddr_AWREADY),
    .AWADDR(m_axi_Out_ddr_AWADDR),
    .AWID(m_axi_Out_ddr_AWID),
    .AWLEN(m_axi_Out_ddr_AWLEN),
    .AWSIZE(m_axi_Out_ddr_AWSIZE),
    .AWBURST(m_axi_Out_ddr_AWBURST),
    .AWLOCK(m_axi_Out_ddr_AWLOCK),
    .AWCACHE(m_axi_Out_ddr_AWCACHE),
    .AWPROT(m_axi_Out_ddr_AWPROT),
    .AWQOS(m_axi_Out_ddr_AWQOS),
    .AWREGION(m_axi_Out_ddr_AWREGION),
    .AWUSER(m_axi_Out_ddr_AWUSER),
    .WVALID(m_axi_Out_ddr_WVALID),
    .WREADY(m_axi_Out_ddr_WREADY),
    .WDATA(m_axi_Out_ddr_WDATA),
    .WSTRB(m_axi_Out_ddr_WSTRB),
    .WLAST(m_axi_Out_ddr_WLAST),
    .WID(m_axi_Out_ddr_WID),
    .WUSER(m_axi_Out_ddr_WUSER),
    .ARVALID(m_axi_Out_ddr_ARVALID),
    .ARREADY(m_axi_Out_ddr_ARREADY),
    .ARADDR(m_axi_Out_ddr_ARADDR),
    .ARID(m_axi_Out_ddr_ARID),
    .ARLEN(m_axi_Out_ddr_ARLEN),
    .ARSIZE(m_axi_Out_ddr_ARSIZE),
    .ARBURST(m_axi_Out_ddr_ARBURST),
    .ARLOCK(m_axi_Out_ddr_ARLOCK),
    .ARCACHE(m_axi_Out_ddr_ARCACHE),
    .ARPROT(m_axi_Out_ddr_ARPROT),
    .ARQOS(m_axi_Out_ddr_ARQOS),
    .ARREGION(m_axi_Out_ddr_ARREGION),
    .ARUSER(m_axi_Out_ddr_ARUSER),
    .RVALID(m_axi_Out_ddr_RVALID),
    .RREADY(m_axi_Out_ddr_RREADY),
    .RDATA(m_axi_Out_ddr_RDATA),
    .RLAST(m_axi_Out_ddr_RLAST),
    .RID(m_axi_Out_ddr_RID),
    .RUSER(m_axi_Out_ddr_RUSER),
    .RRESP(m_axi_Out_ddr_RRESP),
    .BVALID(m_axi_Out_ddr_BVALID),
    .BREADY(m_axi_Out_ddr_BREADY),
    .BRESP(m_axi_Out_ddr_BRESP),
    .BID(m_axi_Out_ddr_BID),
    .BUSER(m_axi_Out_ddr_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(Out_ddr_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(Out_ddr_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(Out_ddr_RDATA),
    .I_RID(Out_ddr_RID),
    .I_RUSER(Out_ddr_RUSER),
    .I_RRESP(Out_ddr_RRESP),
    .I_RLAST(Out_ddr_RLAST),
    .I_AWVALID(Out_ddr_AWVALID),
    .I_AWREADY(Out_ddr_AWREADY),
    .I_AWADDR(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWADDR),
    .I_AWID(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWID),
    .I_AWLEN(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLEN),
    .I_AWSIZE(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWSIZE),
    .I_AWLOCK(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLOCK),
    .I_AWCACHE(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWCACHE),
    .I_AWQOS(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWQOS),
    .I_AWPROT(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWPROT),
    .I_AWUSER(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWUSER),
    .I_AWBURST(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWBURST),
    .I_AWREGION(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWREGION),
    .I_WVALID(Out_ddr_WVALID),
    .I_WREADY(Out_ddr_WREADY),
    .I_WDATA(grp_Offload_Out_fu_260_m_axi_Out_ddr_WDATA),
    .I_WID(grp_Offload_Out_fu_260_m_axi_Out_ddr_WID),
    .I_WUSER(grp_Offload_Out_fu_260_m_axi_Out_ddr_WUSER),
    .I_WLAST(grp_Offload_Out_fu_260_m_axi_Out_ddr_WLAST),
    .I_WSTRB(grp_Offload_Out_fu_260_m_axi_Out_ddr_WSTRB),
    .I_BVALID(Out_ddr_BVALID),
    .I_BREADY(Out_ddr_BREADY),
    .I_BRESP(Out_ddr_BRESP),
    .I_BID(Out_ddr_BID),
    .I_BUSER(Out_ddr_BUSER)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_0_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_0_ce0),
    .q0(Out_0_0_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_1_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_1_ce0),
    .q0(Out_0_1_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_2_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_2_ce0),
    .q0(Out_0_2_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_3_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_3_ce0),
    .q0(Out_0_3_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_4_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_4_ce0),
    .q0(Out_0_4_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_5_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_5_ce0),
    .q0(Out_0_5_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_6_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_6_ce0),
    .q0(Out_0_6_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_7_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_7_ce0),
    .q0(Out_0_7_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_8_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_8_ce0),
    .q0(Out_0_8_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_9_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_9_ce0),
    .q0(Out_0_9_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_10_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_10_ce0),
    .q0(Out_0_10_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_11_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_11_ce0),
    .q0(Out_0_11_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_12_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_12_ce0),
    .q0(Out_0_12_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_0_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_0_13_address0),
    .ce0(grp_Offload_Out_fu_260_Out_0_13_ce0),
    .q0(Out_0_13_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_0_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_0_ce0),
    .q0(Out_1_0_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_1_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_1_ce0),
    .q0(Out_1_1_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_2_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_2_ce0),
    .q0(Out_1_2_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_3_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_3_ce0),
    .q0(Out_1_3_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_4_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_4_ce0),
    .q0(Out_1_4_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_5_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_5_ce0),
    .q0(Out_1_5_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_6_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_6_ce0),
    .q0(Out_1_6_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_7_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_7_ce0),
    .q0(Out_1_7_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_8_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_8_ce0),
    .q0(Out_1_8_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_9_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_9_ce0),
    .q0(Out_1_9_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_10_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_10_ce0),
    .q0(Out_1_10_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_11_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_11_ce0),
    .q0(Out_1_11_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_12_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_12_ce0),
    .q0(Out_1_12_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_1_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_1_13_address0),
    .ce0(grp_Offload_Out_fu_260_Out_1_13_ce0),
    .q0(Out_1_13_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_0_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_0_ce0),
    .q0(Out_2_0_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_1_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_1_ce0),
    .q0(Out_2_1_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_2_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_2_ce0),
    .q0(Out_2_2_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_3_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_3_ce0),
    .q0(Out_2_3_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_4_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_4_ce0),
    .q0(Out_2_4_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_5_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_5_ce0),
    .q0(Out_2_5_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_6_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_6_ce0),
    .q0(Out_2_6_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_7_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_7_ce0),
    .q0(Out_2_7_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_8_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_8_ce0),
    .q0(Out_2_8_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_9_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_9_ce0),
    .q0(Out_2_9_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_10_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_10_ce0),
    .q0(Out_2_10_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_11_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_11_ce0),
    .q0(Out_2_11_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_12_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_12_ce0),
    .q0(Out_2_12_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_2_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_2_13_address0),
    .ce0(grp_Offload_Out_fu_260_Out_2_13_ce0),
    .q0(Out_2_13_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_0_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_0_ce0),
    .q0(Out_3_0_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_1_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_1_ce0),
    .q0(Out_3_1_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_2_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_2_ce0),
    .q0(Out_3_2_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_3_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_3_ce0),
    .q0(Out_3_3_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_4_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_4_ce0),
    .q0(Out_3_4_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_5_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_5_ce0),
    .q0(Out_3_5_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_6_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_6_ce0),
    .q0(Out_3_6_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_7_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_7_ce0),
    .q0(Out_3_7_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_8_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_8_ce0),
    .q0(Out_3_8_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_9_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_9_ce0),
    .q0(Out_3_9_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_10_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_10_ce0),
    .q0(Out_3_10_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_11_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_11_ce0),
    .q0(Out_3_11_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_12_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_12_ce0),
    .q0(Out_3_12_q0)
);

convolution_Out_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
Out_3_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_Offload_Out_fu_260_Out_3_13_address0),
    .ce0(grp_Offload_Out_fu_260_Out_3_13_ce0),
    .q0(Out_3_13_q0)
);

Process_r grp_Process_r_fu_254(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Process_r_fu_254_ap_start),
    .ap_done(grp_Process_r_fu_254_ap_done),
    .ap_idle(grp_Process_r_fu_254_ap_idle),
    .ap_ready(grp_Process_r_fu_254_ap_ready),
    .m_axi_W_ddr_AWVALID(grp_Process_r_fu_254_m_axi_W_ddr_AWVALID),
    .m_axi_W_ddr_AWREADY(1'b0),
    .m_axi_W_ddr_AWADDR(grp_Process_r_fu_254_m_axi_W_ddr_AWADDR),
    .m_axi_W_ddr_AWID(grp_Process_r_fu_254_m_axi_W_ddr_AWID),
    .m_axi_W_ddr_AWLEN(grp_Process_r_fu_254_m_axi_W_ddr_AWLEN),
    .m_axi_W_ddr_AWSIZE(grp_Process_r_fu_254_m_axi_W_ddr_AWSIZE),
    .m_axi_W_ddr_AWBURST(grp_Process_r_fu_254_m_axi_W_ddr_AWBURST),
    .m_axi_W_ddr_AWLOCK(grp_Process_r_fu_254_m_axi_W_ddr_AWLOCK),
    .m_axi_W_ddr_AWCACHE(grp_Process_r_fu_254_m_axi_W_ddr_AWCACHE),
    .m_axi_W_ddr_AWPROT(grp_Process_r_fu_254_m_axi_W_ddr_AWPROT),
    .m_axi_W_ddr_AWQOS(grp_Process_r_fu_254_m_axi_W_ddr_AWQOS),
    .m_axi_W_ddr_AWREGION(grp_Process_r_fu_254_m_axi_W_ddr_AWREGION),
    .m_axi_W_ddr_AWUSER(grp_Process_r_fu_254_m_axi_W_ddr_AWUSER),
    .m_axi_W_ddr_WVALID(grp_Process_r_fu_254_m_axi_W_ddr_WVALID),
    .m_axi_W_ddr_WREADY(1'b0),
    .m_axi_W_ddr_WDATA(grp_Process_r_fu_254_m_axi_W_ddr_WDATA),
    .m_axi_W_ddr_WSTRB(grp_Process_r_fu_254_m_axi_W_ddr_WSTRB),
    .m_axi_W_ddr_WLAST(grp_Process_r_fu_254_m_axi_W_ddr_WLAST),
    .m_axi_W_ddr_WID(grp_Process_r_fu_254_m_axi_W_ddr_WID),
    .m_axi_W_ddr_WUSER(grp_Process_r_fu_254_m_axi_W_ddr_WUSER),
    .m_axi_W_ddr_ARVALID(grp_Process_r_fu_254_m_axi_W_ddr_ARVALID),
    .m_axi_W_ddr_ARREADY(W_ddr_ARREADY),
    .m_axi_W_ddr_ARADDR(grp_Process_r_fu_254_m_axi_W_ddr_ARADDR),
    .m_axi_W_ddr_ARID(grp_Process_r_fu_254_m_axi_W_ddr_ARID),
    .m_axi_W_ddr_ARLEN(grp_Process_r_fu_254_m_axi_W_ddr_ARLEN),
    .m_axi_W_ddr_ARSIZE(grp_Process_r_fu_254_m_axi_W_ddr_ARSIZE),
    .m_axi_W_ddr_ARBURST(grp_Process_r_fu_254_m_axi_W_ddr_ARBURST),
    .m_axi_W_ddr_ARLOCK(grp_Process_r_fu_254_m_axi_W_ddr_ARLOCK),
    .m_axi_W_ddr_ARCACHE(grp_Process_r_fu_254_m_axi_W_ddr_ARCACHE),
    .m_axi_W_ddr_ARPROT(grp_Process_r_fu_254_m_axi_W_ddr_ARPROT),
    .m_axi_W_ddr_ARQOS(grp_Process_r_fu_254_m_axi_W_ddr_ARQOS),
    .m_axi_W_ddr_ARREGION(grp_Process_r_fu_254_m_axi_W_ddr_ARREGION),
    .m_axi_W_ddr_ARUSER(grp_Process_r_fu_254_m_axi_W_ddr_ARUSER),
    .m_axi_W_ddr_RVALID(W_ddr_RVALID),
    .m_axi_W_ddr_RREADY(grp_Process_r_fu_254_m_axi_W_ddr_RREADY),
    .m_axi_W_ddr_RDATA(W_ddr_RDATA),
    .m_axi_W_ddr_RLAST(W_ddr_RLAST),
    .m_axi_W_ddr_RID(W_ddr_RID),
    .m_axi_W_ddr_RUSER(W_ddr_RUSER),
    .m_axi_W_ddr_RRESP(W_ddr_RRESP),
    .m_axi_W_ddr_BVALID(1'b0),
    .m_axi_W_ddr_BREADY(grp_Process_r_fu_254_m_axi_W_ddr_BREADY),
    .m_axi_W_ddr_BRESP(2'd0),
    .m_axi_W_ddr_BID(1'd0),
    .m_axi_W_ddr_BUSER(1'd0)
);

Offload_Out grp_Offload_Out_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Offload_Out_fu_260_ap_start),
    .ap_done(grp_Offload_Out_fu_260_ap_done),
    .ap_idle(grp_Offload_Out_fu_260_ap_idle),
    .ap_ready(grp_Offload_Out_fu_260_ap_ready),
    .m_axi_Out_ddr_AWVALID(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWVALID),
    .m_axi_Out_ddr_AWREADY(Out_ddr_AWREADY),
    .m_axi_Out_ddr_AWADDR(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWADDR),
    .m_axi_Out_ddr_AWID(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWID),
    .m_axi_Out_ddr_AWLEN(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLEN),
    .m_axi_Out_ddr_AWSIZE(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWSIZE),
    .m_axi_Out_ddr_AWBURST(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWBURST),
    .m_axi_Out_ddr_AWLOCK(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWLOCK),
    .m_axi_Out_ddr_AWCACHE(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWCACHE),
    .m_axi_Out_ddr_AWPROT(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWPROT),
    .m_axi_Out_ddr_AWQOS(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWQOS),
    .m_axi_Out_ddr_AWREGION(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWREGION),
    .m_axi_Out_ddr_AWUSER(grp_Offload_Out_fu_260_m_axi_Out_ddr_AWUSER),
    .m_axi_Out_ddr_WVALID(grp_Offload_Out_fu_260_m_axi_Out_ddr_WVALID),
    .m_axi_Out_ddr_WREADY(Out_ddr_WREADY),
    .m_axi_Out_ddr_WDATA(grp_Offload_Out_fu_260_m_axi_Out_ddr_WDATA),
    .m_axi_Out_ddr_WSTRB(grp_Offload_Out_fu_260_m_axi_Out_ddr_WSTRB),
    .m_axi_Out_ddr_WLAST(grp_Offload_Out_fu_260_m_axi_Out_ddr_WLAST),
    .m_axi_Out_ddr_WID(grp_Offload_Out_fu_260_m_axi_Out_ddr_WID),
    .m_axi_Out_ddr_WUSER(grp_Offload_Out_fu_260_m_axi_Out_ddr_WUSER),
    .m_axi_Out_ddr_ARVALID(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARVALID),
    .m_axi_Out_ddr_ARREADY(1'b0),
    .m_axi_Out_ddr_ARADDR(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARADDR),
    .m_axi_Out_ddr_ARID(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARID),
    .m_axi_Out_ddr_ARLEN(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARLEN),
    .m_axi_Out_ddr_ARSIZE(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARSIZE),
    .m_axi_Out_ddr_ARBURST(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARBURST),
    .m_axi_Out_ddr_ARLOCK(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARLOCK),
    .m_axi_Out_ddr_ARCACHE(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARCACHE),
    .m_axi_Out_ddr_ARPROT(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARPROT),
    .m_axi_Out_ddr_ARQOS(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARQOS),
    .m_axi_Out_ddr_ARREGION(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARREGION),
    .m_axi_Out_ddr_ARUSER(grp_Offload_Out_fu_260_m_axi_Out_ddr_ARUSER),
    .m_axi_Out_ddr_RVALID(1'b0),
    .m_axi_Out_ddr_RREADY(grp_Offload_Out_fu_260_m_axi_Out_ddr_RREADY),
    .m_axi_Out_ddr_RDATA(32'd0),
    .m_axi_Out_ddr_RLAST(1'b0),
    .m_axi_Out_ddr_RID(1'd0),
    .m_axi_Out_ddr_RUSER(1'd0),
    .m_axi_Out_ddr_RRESP(2'd0),
    .m_axi_Out_ddr_BVALID(Out_ddr_BVALID),
    .m_axi_Out_ddr_BREADY(grp_Offload_Out_fu_260_m_axi_Out_ddr_BREADY),
    .m_axi_Out_ddr_BRESP(Out_ddr_BRESP),
    .m_axi_Out_ddr_BID(Out_ddr_BID),
    .m_axi_Out_ddr_BUSER(Out_ddr_BUSER),
    .Out_0_0_address0(grp_Offload_Out_fu_260_Out_0_0_address0),
    .Out_0_0_ce0(grp_Offload_Out_fu_260_Out_0_0_ce0),
    .Out_0_0_q0(Out_0_0_q0),
    .Out_0_1_address0(grp_Offload_Out_fu_260_Out_0_1_address0),
    .Out_0_1_ce0(grp_Offload_Out_fu_260_Out_0_1_ce0),
    .Out_0_1_q0(Out_0_1_q0),
    .Out_0_2_address0(grp_Offload_Out_fu_260_Out_0_2_address0),
    .Out_0_2_ce0(grp_Offload_Out_fu_260_Out_0_2_ce0),
    .Out_0_2_q0(Out_0_2_q0),
    .Out_0_3_address0(grp_Offload_Out_fu_260_Out_0_3_address0),
    .Out_0_3_ce0(grp_Offload_Out_fu_260_Out_0_3_ce0),
    .Out_0_3_q0(Out_0_3_q0),
    .Out_0_4_address0(grp_Offload_Out_fu_260_Out_0_4_address0),
    .Out_0_4_ce0(grp_Offload_Out_fu_260_Out_0_4_ce0),
    .Out_0_4_q0(Out_0_4_q0),
    .Out_0_5_address0(grp_Offload_Out_fu_260_Out_0_5_address0),
    .Out_0_5_ce0(grp_Offload_Out_fu_260_Out_0_5_ce0),
    .Out_0_5_q0(Out_0_5_q0),
    .Out_0_6_address0(grp_Offload_Out_fu_260_Out_0_6_address0),
    .Out_0_6_ce0(grp_Offload_Out_fu_260_Out_0_6_ce0),
    .Out_0_6_q0(Out_0_6_q0),
    .Out_0_7_address0(grp_Offload_Out_fu_260_Out_0_7_address0),
    .Out_0_7_ce0(grp_Offload_Out_fu_260_Out_0_7_ce0),
    .Out_0_7_q0(Out_0_7_q0),
    .Out_0_8_address0(grp_Offload_Out_fu_260_Out_0_8_address0),
    .Out_0_8_ce0(grp_Offload_Out_fu_260_Out_0_8_ce0),
    .Out_0_8_q0(Out_0_8_q0),
    .Out_0_9_address0(grp_Offload_Out_fu_260_Out_0_9_address0),
    .Out_0_9_ce0(grp_Offload_Out_fu_260_Out_0_9_ce0),
    .Out_0_9_q0(Out_0_9_q0),
    .Out_0_10_address0(grp_Offload_Out_fu_260_Out_0_10_address0),
    .Out_0_10_ce0(grp_Offload_Out_fu_260_Out_0_10_ce0),
    .Out_0_10_q0(Out_0_10_q0),
    .Out_0_11_address0(grp_Offload_Out_fu_260_Out_0_11_address0),
    .Out_0_11_ce0(grp_Offload_Out_fu_260_Out_0_11_ce0),
    .Out_0_11_q0(Out_0_11_q0),
    .Out_0_12_address0(grp_Offload_Out_fu_260_Out_0_12_address0),
    .Out_0_12_ce0(grp_Offload_Out_fu_260_Out_0_12_ce0),
    .Out_0_12_q0(Out_0_12_q0),
    .Out_0_13_address0(grp_Offload_Out_fu_260_Out_0_13_address0),
    .Out_0_13_ce0(grp_Offload_Out_fu_260_Out_0_13_ce0),
    .Out_0_13_q0(Out_0_13_q0),
    .Out_1_0_address0(grp_Offload_Out_fu_260_Out_1_0_address0),
    .Out_1_0_ce0(grp_Offload_Out_fu_260_Out_1_0_ce0),
    .Out_1_0_q0(Out_1_0_q0),
    .Out_1_1_address0(grp_Offload_Out_fu_260_Out_1_1_address0),
    .Out_1_1_ce0(grp_Offload_Out_fu_260_Out_1_1_ce0),
    .Out_1_1_q0(Out_1_1_q0),
    .Out_1_2_address0(grp_Offload_Out_fu_260_Out_1_2_address0),
    .Out_1_2_ce0(grp_Offload_Out_fu_260_Out_1_2_ce0),
    .Out_1_2_q0(Out_1_2_q0),
    .Out_1_3_address0(grp_Offload_Out_fu_260_Out_1_3_address0),
    .Out_1_3_ce0(grp_Offload_Out_fu_260_Out_1_3_ce0),
    .Out_1_3_q0(Out_1_3_q0),
    .Out_1_4_address0(grp_Offload_Out_fu_260_Out_1_4_address0),
    .Out_1_4_ce0(grp_Offload_Out_fu_260_Out_1_4_ce0),
    .Out_1_4_q0(Out_1_4_q0),
    .Out_1_5_address0(grp_Offload_Out_fu_260_Out_1_5_address0),
    .Out_1_5_ce0(grp_Offload_Out_fu_260_Out_1_5_ce0),
    .Out_1_5_q0(Out_1_5_q0),
    .Out_1_6_address0(grp_Offload_Out_fu_260_Out_1_6_address0),
    .Out_1_6_ce0(grp_Offload_Out_fu_260_Out_1_6_ce0),
    .Out_1_6_q0(Out_1_6_q0),
    .Out_1_7_address0(grp_Offload_Out_fu_260_Out_1_7_address0),
    .Out_1_7_ce0(grp_Offload_Out_fu_260_Out_1_7_ce0),
    .Out_1_7_q0(Out_1_7_q0),
    .Out_1_8_address0(grp_Offload_Out_fu_260_Out_1_8_address0),
    .Out_1_8_ce0(grp_Offload_Out_fu_260_Out_1_8_ce0),
    .Out_1_8_q0(Out_1_8_q0),
    .Out_1_9_address0(grp_Offload_Out_fu_260_Out_1_9_address0),
    .Out_1_9_ce0(grp_Offload_Out_fu_260_Out_1_9_ce0),
    .Out_1_9_q0(Out_1_9_q0),
    .Out_1_10_address0(grp_Offload_Out_fu_260_Out_1_10_address0),
    .Out_1_10_ce0(grp_Offload_Out_fu_260_Out_1_10_ce0),
    .Out_1_10_q0(Out_1_10_q0),
    .Out_1_11_address0(grp_Offload_Out_fu_260_Out_1_11_address0),
    .Out_1_11_ce0(grp_Offload_Out_fu_260_Out_1_11_ce0),
    .Out_1_11_q0(Out_1_11_q0),
    .Out_1_12_address0(grp_Offload_Out_fu_260_Out_1_12_address0),
    .Out_1_12_ce0(grp_Offload_Out_fu_260_Out_1_12_ce0),
    .Out_1_12_q0(Out_1_12_q0),
    .Out_1_13_address0(grp_Offload_Out_fu_260_Out_1_13_address0),
    .Out_1_13_ce0(grp_Offload_Out_fu_260_Out_1_13_ce0),
    .Out_1_13_q0(Out_1_13_q0),
    .Out_2_0_address0(grp_Offload_Out_fu_260_Out_2_0_address0),
    .Out_2_0_ce0(grp_Offload_Out_fu_260_Out_2_0_ce0),
    .Out_2_0_q0(Out_2_0_q0),
    .Out_2_1_address0(grp_Offload_Out_fu_260_Out_2_1_address0),
    .Out_2_1_ce0(grp_Offload_Out_fu_260_Out_2_1_ce0),
    .Out_2_1_q0(Out_2_1_q0),
    .Out_2_2_address0(grp_Offload_Out_fu_260_Out_2_2_address0),
    .Out_2_2_ce0(grp_Offload_Out_fu_260_Out_2_2_ce0),
    .Out_2_2_q0(Out_2_2_q0),
    .Out_2_3_address0(grp_Offload_Out_fu_260_Out_2_3_address0),
    .Out_2_3_ce0(grp_Offload_Out_fu_260_Out_2_3_ce0),
    .Out_2_3_q0(Out_2_3_q0),
    .Out_2_4_address0(grp_Offload_Out_fu_260_Out_2_4_address0),
    .Out_2_4_ce0(grp_Offload_Out_fu_260_Out_2_4_ce0),
    .Out_2_4_q0(Out_2_4_q0),
    .Out_2_5_address0(grp_Offload_Out_fu_260_Out_2_5_address0),
    .Out_2_5_ce0(grp_Offload_Out_fu_260_Out_2_5_ce0),
    .Out_2_5_q0(Out_2_5_q0),
    .Out_2_6_address0(grp_Offload_Out_fu_260_Out_2_6_address0),
    .Out_2_6_ce0(grp_Offload_Out_fu_260_Out_2_6_ce0),
    .Out_2_6_q0(Out_2_6_q0),
    .Out_2_7_address0(grp_Offload_Out_fu_260_Out_2_7_address0),
    .Out_2_7_ce0(grp_Offload_Out_fu_260_Out_2_7_ce0),
    .Out_2_7_q0(Out_2_7_q0),
    .Out_2_8_address0(grp_Offload_Out_fu_260_Out_2_8_address0),
    .Out_2_8_ce0(grp_Offload_Out_fu_260_Out_2_8_ce0),
    .Out_2_8_q0(Out_2_8_q0),
    .Out_2_9_address0(grp_Offload_Out_fu_260_Out_2_9_address0),
    .Out_2_9_ce0(grp_Offload_Out_fu_260_Out_2_9_ce0),
    .Out_2_9_q0(Out_2_9_q0),
    .Out_2_10_address0(grp_Offload_Out_fu_260_Out_2_10_address0),
    .Out_2_10_ce0(grp_Offload_Out_fu_260_Out_2_10_ce0),
    .Out_2_10_q0(Out_2_10_q0),
    .Out_2_11_address0(grp_Offload_Out_fu_260_Out_2_11_address0),
    .Out_2_11_ce0(grp_Offload_Out_fu_260_Out_2_11_ce0),
    .Out_2_11_q0(Out_2_11_q0),
    .Out_2_12_address0(grp_Offload_Out_fu_260_Out_2_12_address0),
    .Out_2_12_ce0(grp_Offload_Out_fu_260_Out_2_12_ce0),
    .Out_2_12_q0(Out_2_12_q0),
    .Out_2_13_address0(grp_Offload_Out_fu_260_Out_2_13_address0),
    .Out_2_13_ce0(grp_Offload_Out_fu_260_Out_2_13_ce0),
    .Out_2_13_q0(Out_2_13_q0),
    .Out_3_0_address0(grp_Offload_Out_fu_260_Out_3_0_address0),
    .Out_3_0_ce0(grp_Offload_Out_fu_260_Out_3_0_ce0),
    .Out_3_0_q0(Out_3_0_q0),
    .Out_3_1_address0(grp_Offload_Out_fu_260_Out_3_1_address0),
    .Out_3_1_ce0(grp_Offload_Out_fu_260_Out_3_1_ce0),
    .Out_3_1_q0(Out_3_1_q0),
    .Out_3_2_address0(grp_Offload_Out_fu_260_Out_3_2_address0),
    .Out_3_2_ce0(grp_Offload_Out_fu_260_Out_3_2_ce0),
    .Out_3_2_q0(Out_3_2_q0),
    .Out_3_3_address0(grp_Offload_Out_fu_260_Out_3_3_address0),
    .Out_3_3_ce0(grp_Offload_Out_fu_260_Out_3_3_ce0),
    .Out_3_3_q0(Out_3_3_q0),
    .Out_3_4_address0(grp_Offload_Out_fu_260_Out_3_4_address0),
    .Out_3_4_ce0(grp_Offload_Out_fu_260_Out_3_4_ce0),
    .Out_3_4_q0(Out_3_4_q0),
    .Out_3_5_address0(grp_Offload_Out_fu_260_Out_3_5_address0),
    .Out_3_5_ce0(grp_Offload_Out_fu_260_Out_3_5_ce0),
    .Out_3_5_q0(Out_3_5_q0),
    .Out_3_6_address0(grp_Offload_Out_fu_260_Out_3_6_address0),
    .Out_3_6_ce0(grp_Offload_Out_fu_260_Out_3_6_ce0),
    .Out_3_6_q0(Out_3_6_q0),
    .Out_3_7_address0(grp_Offload_Out_fu_260_Out_3_7_address0),
    .Out_3_7_ce0(grp_Offload_Out_fu_260_Out_3_7_ce0),
    .Out_3_7_q0(Out_3_7_q0),
    .Out_3_8_address0(grp_Offload_Out_fu_260_Out_3_8_address0),
    .Out_3_8_ce0(grp_Offload_Out_fu_260_Out_3_8_ce0),
    .Out_3_8_q0(Out_3_8_q0),
    .Out_3_9_address0(grp_Offload_Out_fu_260_Out_3_9_address0),
    .Out_3_9_ce0(grp_Offload_Out_fu_260_Out_3_9_ce0),
    .Out_3_9_q0(Out_3_9_q0),
    .Out_3_10_address0(grp_Offload_Out_fu_260_Out_3_10_address0),
    .Out_3_10_ce0(grp_Offload_Out_fu_260_Out_3_10_ce0),
    .Out_3_10_q0(Out_3_10_q0),
    .Out_3_11_address0(grp_Offload_Out_fu_260_Out_3_11_address0),
    .Out_3_11_ce0(grp_Offload_Out_fu_260_Out_3_11_ce0),
    .Out_3_11_q0(Out_3_11_q0),
    .Out_3_12_address0(grp_Offload_Out_fu_260_Out_3_12_address0),
    .Out_3_12_ce0(grp_Offload_Out_fu_260_Out_3_12_ce0),
    .Out_3_12_q0(Out_3_12_q0),
    .Out_3_13_address0(grp_Offload_Out_fu_260_Out_3_13_address0),
    .Out_3_13_ce0(grp_Offload_Out_fu_260_Out_3_13_ce0),
    .Out_3_13_q0(Out_3_13_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Offload_Out_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Offload_Out_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_Offload_Out_fu_260_ap_ready == 1'b1)) begin
            grp_Offload_Out_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Process_r_fu_254_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Process_r_fu_254_ap_start_reg <= 1'b1;
        end else if ((grp_Process_r_fu_254_ap_ready == 1'b1)) begin
            grp_Process_r_fu_254_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        Out_ddr_AWVALID = grp_Offload_Out_fu_260_m_axi_Out_ddr_AWVALID;
    end else begin
        Out_ddr_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        Out_ddr_BREADY = grp_Offload_Out_fu_260_m_axi_Out_ddr_BREADY;
    end else begin
        Out_ddr_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        Out_ddr_WVALID = grp_Offload_Out_fu_260_m_axi_Out_ddr_WVALID;
    end else begin
        Out_ddr_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        W_ddr_ARVALID = grp_Process_r_fu_254_m_axi_W_ddr_ARVALID;
    end else begin
        W_ddr_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        W_ddr_RREADY = grp_Process_r_fu_254_m_axi_W_ddr_RREADY;
    end else begin
        W_ddr_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_Offload_Out_fu_260_ap_done == 1'b0) | (grp_Process_r_fu_254_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_Offload_Out_fu_260_ap_start = grp_Offload_Out_fu_260_ap_start_reg;

assign grp_Process_r_fu_254_ap_start = grp_Process_r_fu_254_ap_start_reg;

assign m_axi_In_ddr_ARADDR = 32'd0;

assign m_axi_In_ddr_ARBURST = 2'd0;

assign m_axi_In_ddr_ARCACHE = 4'd0;

assign m_axi_In_ddr_ARID = 1'd0;

assign m_axi_In_ddr_ARLEN = 8'd0;

assign m_axi_In_ddr_ARLOCK = 2'd0;

assign m_axi_In_ddr_ARPROT = 3'd0;

assign m_axi_In_ddr_ARQOS = 4'd0;

assign m_axi_In_ddr_ARREGION = 4'd0;

assign m_axi_In_ddr_ARSIZE = 3'd0;

assign m_axi_In_ddr_ARUSER = 1'd0;

assign m_axi_In_ddr_ARVALID = 1'b0;

assign m_axi_In_ddr_AWADDR = 32'd0;

assign m_axi_In_ddr_AWBURST = 2'd0;

assign m_axi_In_ddr_AWCACHE = 4'd0;

assign m_axi_In_ddr_AWID = 1'd0;

assign m_axi_In_ddr_AWLEN = 8'd0;

assign m_axi_In_ddr_AWLOCK = 2'd0;

assign m_axi_In_ddr_AWPROT = 3'd0;

assign m_axi_In_ddr_AWQOS = 4'd0;

assign m_axi_In_ddr_AWREGION = 4'd0;

assign m_axi_In_ddr_AWSIZE = 3'd0;

assign m_axi_In_ddr_AWUSER = 1'd0;

assign m_axi_In_ddr_AWVALID = 1'b0;

assign m_axi_In_ddr_BREADY = 1'b0;

assign m_axi_In_ddr_RREADY = 1'b0;

assign m_axi_In_ddr_WDATA = 32'd0;

assign m_axi_In_ddr_WID = 1'd0;

assign m_axi_In_ddr_WLAST = 1'b0;

assign m_axi_In_ddr_WSTRB = 4'd0;

assign m_axi_In_ddr_WUSER = 1'd0;

assign m_axi_In_ddr_WVALID = 1'b0;

endmodule //convolution
