// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    ap_const_lv32_0 = 32'd0;




input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
input   do_cos;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] ref_4oPi_table_256_V_address0;
reg    ref_4oPi_table_256_V_ce0;
wire   [255:0] ref_4oPi_table_256_V_q0;
wire   [7:0] fourth_order_double_4_address0;
reg    fourth_order_double_4_ce0;
wire   [58:0] fourth_order_double_4_q0;
wire   [7:0] fourth_order_double_5_address0;
reg    fourth_order_double_5_ce0;
wire   [51:0] fourth_order_double_5_q0;
wire   [7:0] fourth_order_double_6_address0;
reg    fourth_order_double_6_ce0;
wire   [43:0] fourth_order_double_6_q0;
wire   [7:0] fourth_order_double_7_address0;
reg    fourth_order_double_7_ce0;
wire   [32:0] fourth_order_double_7_q0;
wire   [7:0] fourth_order_double_s_address0;
reg    fourth_order_double_s_ce0;
wire   [24:0] fourth_order_double_s_q0;
reg   [0:0] do_cos_read_reg_1529;
reg   [0:0] do_cos_read_reg_1529_pp0_iter1_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter2_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter3_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter4_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter5_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter6_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter7_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter8_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter9_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter10_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter11_reg;
reg   [0:0] do_cos_read_reg_1529_pp0_iter12_reg;
reg   [0:0] p_Result_s_reg_1536;
reg   [0:0] p_Result_s_reg_1536_pp0_iter1_reg;
reg   [0:0] p_Result_s_reg_1536_pp0_iter2_reg;
reg   [0:0] p_Result_s_reg_1536_pp0_iter3_reg;
reg   [0:0] p_Result_s_reg_1536_pp0_iter4_reg;
wire   [10:0] tmp_V_fu_320_p4;
reg   [10:0] tmp_V_reg_1542;
reg   [10:0] tmp_V_reg_1542_pp0_iter1_reg;
reg   [10:0] tmp_V_reg_1542_pp0_iter2_reg;
reg   [10:0] tmp_V_reg_1542_pp0_iter3_reg;
wire   [51:0] tmp_V_1_fu_330_p1;
reg   [51:0] tmp_V_1_reg_1549;
reg   [51:0] tmp_V_1_reg_1549_pp0_iter1_reg;
wire   [0:0] closepath_fu_334_p2;
reg   [0:0] closepath_reg_1555;
reg   [0:0] closepath_reg_1555_pp0_iter1_reg;
reg   [0:0] closepath_reg_1555_pp0_iter2_reg;
reg   [0:0] closepath_reg_1555_pp0_iter3_reg;
wire   [6:0] trunc_ln601_fu_369_p1;
reg   [6:0] trunc_ln601_reg_1566;
reg   [169:0] ret_V_14_reg_1571;
wire   [0:0] icmp_ln833_1_fu_412_p2;
reg   [0:0] icmp_ln833_1_reg_1586;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter3_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter4_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter5_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter6_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter7_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter8_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter9_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter10_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter11_reg;
reg   [0:0] icmp_ln833_1_reg_1586_pp0_iter12_reg;
reg   [123:0] p_Val2_36_reg_1592;
reg   [2:0] trunc_ln_i_reg_1598;
wire   [2:0] p_Val2_37_fu_449_p3;
reg   [2:0] p_Val2_37_reg_1603;
wire   [123:0] p_Val2_7_fu_464_p3;
reg   [123:0] p_Val2_7_reg_1609;
wire   [5:0] Mx_zeros_V_fu_515_p1;
reg   [5:0] Mx_zeros_V_reg_1614;
wire  signed [10:0] Ex_V_fu_523_p2;
reg  signed [10:0] Ex_V_reg_1619;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter5_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter6_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter7_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter8_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter9_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter10_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter11_reg;
reg  signed [10:0] Ex_V_reg_1619_pp0_iter12_reg;
reg   [0:0] isNeg_reg_1625;
wire   [0:0] icmp_ln833_fu_537_p2;
reg   [0:0] icmp_ln833_reg_1631;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter5_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter6_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter7_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter8_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter9_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter10_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter11_reg;
reg   [0:0] icmp_ln833_reg_1631_pp0_iter12_reg;
wire   [0:0] icmp_ln833_2_fu_542_p2;
reg   [0:0] icmp_ln833_2_reg_1637;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter5_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter6_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter7_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter8_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter9_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter10_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter11_reg;
reg   [0:0] icmp_ln833_2_reg_1637_pp0_iter12_reg;
wire   [62:0] Mx_V_fu_555_p4;
reg   [62:0] Mx_V_reg_1645;
reg   [62:0] Mx_V_reg_1645_pp0_iter6_reg;
reg   [62:0] Mx_V_reg_1645_pp0_iter7_reg;
reg   [62:0] Mx_V_reg_1645_pp0_iter8_reg;
wire   [0:0] cos_basis_fu_635_p3;
reg   [0:0] cos_basis_reg_1650;
reg   [0:0] cos_basis_reg_1650_pp0_iter6_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter7_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter8_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter9_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter10_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter11_reg;
reg   [0:0] cos_basis_reg_1650_pp0_iter12_reg;
wire   [55:0] B_V_fu_652_p1;
reg   [55:0] B_V_reg_1656;
reg   [55:0] B_V_reg_1656_pp0_iter6_reg;
reg   [48:0] B_trunc_V_reg_1661;
wire   [63:0] zext_ln498_fu_685_p1;
reg   [63:0] zext_ln498_reg_1666;
wire   [0:0] and_ln300_fu_781_p2;
reg   [0:0] and_ln300_reg_1683;
reg   [0:0] and_ln300_reg_1683_pp0_iter6_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter7_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter8_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter9_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter10_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter11_reg;
reg   [0:0] and_ln300_reg_1683_pp0_iter12_reg;
wire   [0:0] p_Repl2_2_fu_801_p3;
reg   [0:0] p_Repl2_2_reg_1689;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter6_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter7_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter8_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter9_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter10_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter11_reg;
reg   [0:0] p_Repl2_2_reg_1689_pp0_iter12_reg;
wire   [97:0] r_V_5_fu_809_p1;
reg   [97:0] r_V_5_reg_1694;
reg   [48:0] B_squared_V_reg_1699;
reg  signed [51:0] fourth_order_double_10_reg_1710;
reg   [43:0] fourth_order_double_12_reg_1715;
reg   [41:0] B_third_power_V_reg_1730;
reg   [34:0] B_fourth_power_V_reg_1735;
reg   [58:0] p_Val2_15_reg_1740;
reg   [58:0] p_Val2_15_reg_1740_pp0_iter8_reg;
reg   [47:0] trunc_ln662_1_reg_1755;
reg   [47:0] trunc_ln662_1_reg_1755_pp0_iter8_reg;
reg   [32:0] fourth_order_double_14_reg_1760;
reg   [24:0] fourth_order_double_16_reg_1765;
reg   [55:0] trunc_ln1_reg_1770;
reg   [36:0] tmp_3_reg_1775;
reg   [28:0] tmp_4_reg_1780;
wire   [62:0] select_ln272_1_fu_950_p3;
reg   [62:0] select_ln272_1_reg_1785;
wire   [63:0] ret_V_fu_997_p2;
reg  signed [63:0] ret_V_reg_1790;
reg   [62:0] result_V_reg_1805;
reg   [15:0] p_Result_1_i_reg_1811;
reg   [15:0] p_Result_13_1_i_reg_1816;
reg   [15:0] p_Result_13_2_i_reg_1821;
reg   [14:0] p_Result_i_40_reg_1826;
reg   [14:0] p_Result_i_40_reg_1826_pp0_iter12_reg;
reg   [31:0] tmp_i_i2_fu_1132_p3;
reg   [31:0] tmp_i_i2_reg_1831;
reg   [31:0] tmp_i2_i_fu_1150_p3;
reg   [31:0] tmp_i2_i_reg_1837;
reg   [31:0] tmp_i4_i_fu_1168_p3;
reg   [31:0] tmp_i4_i_reg_1843;
wire   [62:0] shl_ln1253_fu_1180_p2;
reg   [62:0] shl_ln1253_reg_1850;
wire   [62:0] shl_ln1253_1_fu_1189_p2;
reg   [62:0] shl_ln1253_1_reg_1855;
wire   [0:0] icmp_ln1452_fu_1195_p2;
reg   [0:0] icmp_ln1452_reg_1861;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln635_fu_364_p1;
wire   [63:0] p_Val2_s_fu_308_p1;
wire   [10:0] add_ln114_1_fu_340_p2;
wire   [10:0] addr_V_fu_346_p3;
wire   [3:0] p_Result_i_i_fu_354_p4;
wire   [255:0] zext_ln744_fu_373_p1;
wire   [255:0] r_V_17_fu_376_p2;
wire   [52:0] p_Result_20_fu_392_p3;
wire   [169:0] grp_fu_406_p0;
wire   [52:0] grp_fu_406_p1;
wire   [222:0] grp_fu_406_p2;
wire   [10:0] add_ln114_fu_437_p2;
wire   [0:0] trunc_ln745_fu_455_p1;
wire   [123:0] Mx_bits_V_1_fu_459_p2;
wire   [60:0] p_Result_i_i_39_fu_471_p4;
wire   [61:0] p_Result_21_fu_481_p3;
reg   [61:0] p_Result_8_fu_489_p4;
wire   [63:0] p_Result_22_fu_499_p3;
reg   [63:0] tmp_i_i_fu_507_p3;
wire   [10:0] select_ln482_fu_442_p3;
wire   [10:0] zext_ln655_fu_519_p1;
wire   [123:0] zext_ln1253_fu_547_p1;
wire   [123:0] r_V_18_fu_550_p2;
wire  signed [11:0] sext_ln1334_fu_565_p1;
wire   [11:0] sub_ln1311_fu_568_p2;
wire   [11:0] ush_fu_574_p3;
wire  signed [31:0] sext_ln1311_fu_581_p1;
wire   [62:0] zext_ln1287_fu_585_p1;
wire   [62:0] r_V_fu_589_p2;
wire   [62:0] r_V_3_fu_595_p2;
wire   [0:0] tmp_1_fu_608_p10;
wire   [0:0] xor_ln271_fu_629_p2;
wire   [62:0] r_V_19_fu_601_p3;
wire   [0:0] xor_ln29_fu_666_p2;
wire   [0:0] sin_basis_fu_671_p2;
wire   [6:0] p_Result_i_fu_642_p4;
wire   [7:0] p_Result_23_fu_677_p3;
wire   [3:0] p_Result_29_fu_691_p3;
wire   [0:0] tmp_fu_697_p18;
wire   [0:0] tmp_2_fu_735_p18;
wire   [0:0] select_ln271_fu_773_p3;
wire   [0:0] xor_ln311_fu_790_p2;
wire   [0:0] and_ln307_fu_785_p2;
wire   [0:0] and_ln311_fu_795_p2;
wire   [48:0] r_V_20_fu_812_p0;
wire   [48:0] r_V_20_fu_812_p1;
wire   [97:0] r_V_20_fu_812_p2;
wire   [48:0] r_V_21_fu_831_p0;
wire   [48:0] r_V_21_fu_831_p1;
wire   [97:0] r_V_8_fu_828_p1;
wire   [97:0] r_V_21_fu_831_p2;
wire   [48:0] r_V_22_fu_846_p0;
wire   [48:0] r_V_22_fu_846_p1;
wire   [97:0] r_V_22_fu_846_p2;
wire   [55:0] grp_fu_868_p0;
wire   [48:0] r_V_24_fu_880_p0;
wire  signed [43:0] r_V_24_fu_880_p1;
wire   [92:0] r_V_24_fu_880_p2;
wire   [107:0] grp_fu_868_p2;
wire   [41:0] r_V_25_fu_912_p0;
wire   [32:0] r_V_25_fu_912_p1;
wire   [74:0] r_V_25_fu_912_p2;
wire   [34:0] r_V_26_fu_934_p0;
wire   [24:0] r_V_26_fu_934_p1;
wire   [59:0] r_V_26_fu_934_p2;
wire   [62:0] t1_V_fu_956_p3;
wire  signed [63:0] lhs_V_1_fu_963_p1;
wire  signed [63:0] rhs_V_2_fu_967_p1;
wire   [63:0] ret_V_16_fu_970_p2;
wire  signed [63:0] sext_ln657_fu_976_p1;
wire   [63:0] ret_V_17_fu_979_p2;
wire   [63:0] zext_ln657_fu_985_p1;
wire   [63:0] ret_V_18_fu_988_p2;
wire   [63:0] zext_ln657_1_fu_994_p1;
wire   [62:0] grp_fu_1009_p1;
wire   [125:0] grp_fu_1009_p2;
wire   [16:0] tmp_i_fu_1065_p3;
wire   [16:0] tmp_4_i_fu_1084_p3;
wire   [16:0] tmp_5_i_fu_1103_p3;
wire   [31:0] p_Val2_27_fu_1072_p5;
reg   [31:0] p_Result_25_fu_1122_p4;
wire   [31:0] p_Val2_28_fu_1091_p5;
reg   [31:0] p_Result_26_fu_1140_p4;
wire   [31:0] p_Val2_29_fu_1110_p5;
reg   [31:0] p_Result_27_fu_1158_p4;
wire   [62:0] zext_ln1287_1_fu_1176_p1;
wire   [62:0] zext_ln1287_2_fu_1185_p1;
wire   [10:0] select_ln272_fu_1200_p3;
wire   [15:0] tmp_6_i_fu_1210_p3;
wire   [31:0] p_Result_24_fu_1217_p5;
reg   [31:0] p_Result_28_fu_1229_p4;
wire   [31:0] add_ln442_fu_1252_p2;
wire   [62:0] zext_ln1287_3_fu_1267_p1;
wire   [31:0] add_ln442_1_fu_1262_p2;
reg   [31:0] tmp_i6_i_fu_1239_p3;
wire   [62:0] shl_ln1253_2_fu_1270_p2;
wire   [62:0] zext_ln1287_4_fu_1286_p1;
wire   [0:0] icmp_ln444_1_fu_1257_p2;
wire   [0:0] icmp_ln444_fu_1247_p2;
wire   [0:0] xor_ln444_fu_1296_p2;
wire   [0:0] icmp_ln444_2_fu_1275_p2;
wire   [0:0] and_ln444_1_fu_1308_p2;
wire   [0:0] and_ln444_2_fu_1314_p2;
wire   [0:0] and_ln444_fu_1302_p2;
wire   [31:0] add_ln442_2_fu_1280_p2;
wire   [0:0] or_ln444_fu_1320_p2;
wire   [31:0] select_ln444_fu_1326_p3;
wire   [31:0] select_ln444_1_fu_1334_p3;
wire  signed [11:0] rhs_V_fu_1206_p1;
wire   [11:0] add_ln452_fu_1349_p2;
wire  signed [31:0] sext_ln452_fu_1355_p1;
wire   [31:0] select_ln444_2_fu_1341_p3;
wire   [31:0] newexp_fu_1359_p2;
wire   [0:0] tmp_11_fu_1365_p3;
wire   [62:0] shl_ln1253_3_fu_1290_p2;
wire   [51:0] tmp_5_fu_1382_p4;
wire   [51:0] tmp_6_fu_1392_p4;
wire   [51:0] tmp_7_fu_1409_p4;
wire   [51:0] tmp_8_fu_1419_p4;
wire   [51:0] select_ln444_3_fu_1401_p3;
wire   [51:0] select_ln444_4_fu_1428_p3;
wire   [0:0] or_ln453_fu_1373_p2;
wire   [51:0] select_ln444_5_fu_1436_p3;
wire   [0:0] or_ln311_fu_1466_p2;
wire   [10:0] select_ln311_1_fu_1459_p3;
wire   [10:0] empty_fu_1378_p1;
wire   [10:0] select_ln307_fu_1452_p3;
wire   [10:0] select_ln311_fu_1471_p3;
wire   [0:0] and_ln300_1_fu_1486_p2;
wire   [0:0] xor_ln300_fu_1490_p2;
wire   [0:0] or_ln300_fu_1504_p2;
wire   [51:0] select_ln300_2_fu_1496_p3;
wire   [51:0] significand_V_fu_1444_p3;
wire   [10:0] ret_V_12_fu_1479_p3;
wire   [51:0] ret_V_13_fu_1508_p3;
wire   [63:0] p_Result_30_fu_1516_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to12;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [125:0] grp_fu_1009_p10;
wire   [222:0] grp_fu_406_p00;
wire   [222:0] grp_fu_406_p10;
wire   [107:0] grp_fu_868_p00;
wire   [92:0] r_V_24_fu_880_p00;
wire   [74:0] r_V_25_fu_912_p00;
wire   [74:0] r_V_25_fu_912_p10;
wire   [59:0] r_V_26_fu_934_p00;
wire   [59:0] r_V_26_fu_934_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
end

sin_or_cos_doublebkb #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ref_4oPi_table_256_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_256_V_address0),
    .ce0(ref_4oPi_table_256_V_ce0),
    .q0(ref_4oPi_table_256_V_q0)
);

sin_or_cos_doublecud #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_4_address0),
    .ce0(fourth_order_double_4_ce0),
    .q0(fourth_order_double_4_q0)
);

sin_or_cos_doubledEe #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_5_address0),
    .ce0(fourth_order_double_5_ce0),
    .q0(fourth_order_double_5_q0)
);

sin_or_cos_doubleeOg #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_6_address0),
    .ce0(fourth_order_double_6_ce0),
    .q0(fourth_order_double_6_q0)
);

sin_or_cos_doublefYi #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_7_address0),
    .ce0(fourth_order_double_7_ce0),
    .q0(fourth_order_double_7_q0)
);

sin_or_cos_doubleg8j #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_s_address0),
    .ce0(fourth_order_double_s_ce0),
    .q0(fourth_order_double_s_q0)
);

dft_mul_170ns_53nhbi #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 170 ),
    .din1_WIDTH( 53 ),
    .dout_WIDTH( 223 ))
dft_mul_170ns_53nhbi_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .ce(1'b1),
    .dout(grp_fu_406_p2)
);

dft_mux_83_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
dft_mux_83_1_1_1_U2(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(p_Val2_37_reg_1603),
    .dout(tmp_1_fu_608_p10)
);

dft_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
dft_mux_164_1_1_1_U3(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_29_fu_691_p3),
    .dout(tmp_fu_697_p18)
);

dft_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
dft_mux_164_1_1_1_U4(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_29_fu_691_p3),
    .dout(tmp_2_fu_735_p18)
);

dft_mul_56ns_52s_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 56 ),
    .din1_WIDTH( 52 ),
    .dout_WIDTH( 108 ))
dft_mul_56ns_52s_ibs_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_868_p0),
    .din1(fourth_order_double_10_reg_1710),
    .ce(1'b1),
    .dout(grp_fu_868_p2)
);

dft_mul_64s_63ns_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 63 ),
    .dout_WIDTH( 126 ))
dft_mul_64s_63ns_jbC_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_reg_1790),
    .din1(grp_fu_1009_p1),
    .ce(1'b1),
    .dout(grp_fu_1009_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        B_V_reg_1656 <= B_V_fu_652_p1;
        B_V_reg_1656_pp0_iter6_reg <= B_V_reg_1656;
        B_fourth_power_V_reg_1735 <= {{r_V_22_fu_846_p2[97:63]}};
        B_squared_V_reg_1699 <= {{r_V_20_fu_812_p2[97:49]}};
        B_third_power_V_reg_1730 <= {{r_V_21_fu_831_p2[97:56]}};
        B_trunc_V_reg_1661 <= {{r_V_19_fu_601_p3[55:7]}};
        Ex_V_reg_1619 <= Ex_V_fu_523_p2;
        Ex_V_reg_1619_pp0_iter10_reg <= Ex_V_reg_1619_pp0_iter9_reg;
        Ex_V_reg_1619_pp0_iter11_reg <= Ex_V_reg_1619_pp0_iter10_reg;
        Ex_V_reg_1619_pp0_iter12_reg <= Ex_V_reg_1619_pp0_iter11_reg;
        Ex_V_reg_1619_pp0_iter5_reg <= Ex_V_reg_1619;
        Ex_V_reg_1619_pp0_iter6_reg <= Ex_V_reg_1619_pp0_iter5_reg;
        Ex_V_reg_1619_pp0_iter7_reg <= Ex_V_reg_1619_pp0_iter6_reg;
        Ex_V_reg_1619_pp0_iter8_reg <= Ex_V_reg_1619_pp0_iter7_reg;
        Ex_V_reg_1619_pp0_iter9_reg <= Ex_V_reg_1619_pp0_iter8_reg;
        Mx_V_reg_1645 <= {{r_V_18_fu_550_p2[123:61]}};
        Mx_V_reg_1645_pp0_iter6_reg <= Mx_V_reg_1645;
        Mx_V_reg_1645_pp0_iter7_reg <= Mx_V_reg_1645_pp0_iter6_reg;
        Mx_V_reg_1645_pp0_iter8_reg <= Mx_V_reg_1645_pp0_iter7_reg;
        Mx_zeros_V_reg_1614 <= Mx_zeros_V_fu_515_p1;
        and_ln300_reg_1683 <= and_ln300_fu_781_p2;
        and_ln300_reg_1683_pp0_iter10_reg <= and_ln300_reg_1683_pp0_iter9_reg;
        and_ln300_reg_1683_pp0_iter11_reg <= and_ln300_reg_1683_pp0_iter10_reg;
        and_ln300_reg_1683_pp0_iter12_reg <= and_ln300_reg_1683_pp0_iter11_reg;
        and_ln300_reg_1683_pp0_iter6_reg <= and_ln300_reg_1683;
        and_ln300_reg_1683_pp0_iter7_reg <= and_ln300_reg_1683_pp0_iter6_reg;
        and_ln300_reg_1683_pp0_iter8_reg <= and_ln300_reg_1683_pp0_iter7_reg;
        and_ln300_reg_1683_pp0_iter9_reg <= and_ln300_reg_1683_pp0_iter8_reg;
        closepath_reg_1555_pp0_iter2_reg <= closepath_reg_1555_pp0_iter1_reg;
        closepath_reg_1555_pp0_iter3_reg <= closepath_reg_1555_pp0_iter2_reg;
        cos_basis_reg_1650 <= cos_basis_fu_635_p3;
        cos_basis_reg_1650_pp0_iter10_reg <= cos_basis_reg_1650_pp0_iter9_reg;
        cos_basis_reg_1650_pp0_iter11_reg <= cos_basis_reg_1650_pp0_iter10_reg;
        cos_basis_reg_1650_pp0_iter12_reg <= cos_basis_reg_1650_pp0_iter11_reg;
        cos_basis_reg_1650_pp0_iter6_reg <= cos_basis_reg_1650;
        cos_basis_reg_1650_pp0_iter7_reg <= cos_basis_reg_1650_pp0_iter6_reg;
        cos_basis_reg_1650_pp0_iter8_reg <= cos_basis_reg_1650_pp0_iter7_reg;
        cos_basis_reg_1650_pp0_iter9_reg <= cos_basis_reg_1650_pp0_iter8_reg;
        do_cos_read_reg_1529_pp0_iter10_reg <= do_cos_read_reg_1529_pp0_iter9_reg;
        do_cos_read_reg_1529_pp0_iter11_reg <= do_cos_read_reg_1529_pp0_iter10_reg;
        do_cos_read_reg_1529_pp0_iter12_reg <= do_cos_read_reg_1529_pp0_iter11_reg;
        do_cos_read_reg_1529_pp0_iter2_reg <= do_cos_read_reg_1529_pp0_iter1_reg;
        do_cos_read_reg_1529_pp0_iter3_reg <= do_cos_read_reg_1529_pp0_iter2_reg;
        do_cos_read_reg_1529_pp0_iter4_reg <= do_cos_read_reg_1529_pp0_iter3_reg;
        do_cos_read_reg_1529_pp0_iter5_reg <= do_cos_read_reg_1529_pp0_iter4_reg;
        do_cos_read_reg_1529_pp0_iter6_reg <= do_cos_read_reg_1529_pp0_iter5_reg;
        do_cos_read_reg_1529_pp0_iter7_reg <= do_cos_read_reg_1529_pp0_iter6_reg;
        do_cos_read_reg_1529_pp0_iter8_reg <= do_cos_read_reg_1529_pp0_iter7_reg;
        do_cos_read_reg_1529_pp0_iter9_reg <= do_cos_read_reg_1529_pp0_iter8_reg;
        fourth_order_double_10_reg_1710 <= fourth_order_double_5_q0;
        fourth_order_double_12_reg_1715 <= fourth_order_double_6_q0;
        fourth_order_double_14_reg_1760 <= fourth_order_double_7_q0;
        fourth_order_double_16_reg_1765 <= fourth_order_double_s_q0;
        icmp_ln1452_reg_1861 <= icmp_ln1452_fu_1195_p2;
        icmp_ln833_1_reg_1586 <= icmp_ln833_1_fu_412_p2;
        icmp_ln833_1_reg_1586_pp0_iter10_reg <= icmp_ln833_1_reg_1586_pp0_iter9_reg;
        icmp_ln833_1_reg_1586_pp0_iter11_reg <= icmp_ln833_1_reg_1586_pp0_iter10_reg;
        icmp_ln833_1_reg_1586_pp0_iter12_reg <= icmp_ln833_1_reg_1586_pp0_iter11_reg;
        icmp_ln833_1_reg_1586_pp0_iter3_reg <= icmp_ln833_1_reg_1586;
        icmp_ln833_1_reg_1586_pp0_iter4_reg <= icmp_ln833_1_reg_1586_pp0_iter3_reg;
        icmp_ln833_1_reg_1586_pp0_iter5_reg <= icmp_ln833_1_reg_1586_pp0_iter4_reg;
        icmp_ln833_1_reg_1586_pp0_iter6_reg <= icmp_ln833_1_reg_1586_pp0_iter5_reg;
        icmp_ln833_1_reg_1586_pp0_iter7_reg <= icmp_ln833_1_reg_1586_pp0_iter6_reg;
        icmp_ln833_1_reg_1586_pp0_iter8_reg <= icmp_ln833_1_reg_1586_pp0_iter7_reg;
        icmp_ln833_1_reg_1586_pp0_iter9_reg <= icmp_ln833_1_reg_1586_pp0_iter8_reg;
        icmp_ln833_2_reg_1637 <= icmp_ln833_2_fu_542_p2;
        icmp_ln833_2_reg_1637_pp0_iter10_reg <= icmp_ln833_2_reg_1637_pp0_iter9_reg;
        icmp_ln833_2_reg_1637_pp0_iter11_reg <= icmp_ln833_2_reg_1637_pp0_iter10_reg;
        icmp_ln833_2_reg_1637_pp0_iter12_reg <= icmp_ln833_2_reg_1637_pp0_iter11_reg;
        icmp_ln833_2_reg_1637_pp0_iter5_reg <= icmp_ln833_2_reg_1637;
        icmp_ln833_2_reg_1637_pp0_iter6_reg <= icmp_ln833_2_reg_1637_pp0_iter5_reg;
        icmp_ln833_2_reg_1637_pp0_iter7_reg <= icmp_ln833_2_reg_1637_pp0_iter6_reg;
        icmp_ln833_2_reg_1637_pp0_iter8_reg <= icmp_ln833_2_reg_1637_pp0_iter7_reg;
        icmp_ln833_2_reg_1637_pp0_iter9_reg <= icmp_ln833_2_reg_1637_pp0_iter8_reg;
        icmp_ln833_reg_1631 <= icmp_ln833_fu_537_p2;
        icmp_ln833_reg_1631_pp0_iter10_reg <= icmp_ln833_reg_1631_pp0_iter9_reg;
        icmp_ln833_reg_1631_pp0_iter11_reg <= icmp_ln833_reg_1631_pp0_iter10_reg;
        icmp_ln833_reg_1631_pp0_iter12_reg <= icmp_ln833_reg_1631_pp0_iter11_reg;
        icmp_ln833_reg_1631_pp0_iter5_reg <= icmp_ln833_reg_1631;
        icmp_ln833_reg_1631_pp0_iter6_reg <= icmp_ln833_reg_1631_pp0_iter5_reg;
        icmp_ln833_reg_1631_pp0_iter7_reg <= icmp_ln833_reg_1631_pp0_iter6_reg;
        icmp_ln833_reg_1631_pp0_iter8_reg <= icmp_ln833_reg_1631_pp0_iter7_reg;
        icmp_ln833_reg_1631_pp0_iter9_reg <= icmp_ln833_reg_1631_pp0_iter8_reg;
        isNeg_reg_1625 <= Ex_V_fu_523_p2[32'd10];
        p_Repl2_2_reg_1689 <= p_Repl2_2_fu_801_p3;
        p_Repl2_2_reg_1689_pp0_iter10_reg <= p_Repl2_2_reg_1689_pp0_iter9_reg;
        p_Repl2_2_reg_1689_pp0_iter11_reg <= p_Repl2_2_reg_1689_pp0_iter10_reg;
        p_Repl2_2_reg_1689_pp0_iter12_reg <= p_Repl2_2_reg_1689_pp0_iter11_reg;
        p_Repl2_2_reg_1689_pp0_iter6_reg <= p_Repl2_2_reg_1689;
        p_Repl2_2_reg_1689_pp0_iter7_reg <= p_Repl2_2_reg_1689_pp0_iter6_reg;
        p_Repl2_2_reg_1689_pp0_iter8_reg <= p_Repl2_2_reg_1689_pp0_iter7_reg;
        p_Repl2_2_reg_1689_pp0_iter9_reg <= p_Repl2_2_reg_1689_pp0_iter8_reg;
        p_Result_13_1_i_reg_1816 <= {{grp_fu_1009_p2[109:94]}};
        p_Result_13_2_i_reg_1821 <= {{grp_fu_1009_p2[93:78]}};
        p_Result_1_i_reg_1811 <= {{grp_fu_1009_p2[125:110]}};
        p_Result_i_40_reg_1826 <= {{grp_fu_1009_p2[77:63]}};
        p_Result_i_40_reg_1826_pp0_iter12_reg <= p_Result_i_40_reg_1826;
        p_Result_s_reg_1536_pp0_iter2_reg <= p_Result_s_reg_1536_pp0_iter1_reg;
        p_Result_s_reg_1536_pp0_iter3_reg <= p_Result_s_reg_1536_pp0_iter2_reg;
        p_Result_s_reg_1536_pp0_iter4_reg <= p_Result_s_reg_1536_pp0_iter3_reg;
        p_Val2_15_reg_1740 <= fourth_order_double_4_q0;
        p_Val2_15_reg_1740_pp0_iter8_reg <= p_Val2_15_reg_1740;
        p_Val2_36_reg_1592 <= {{grp_fu_406_p2[166:43]}};
        p_Val2_37_reg_1603 <= p_Val2_37_fu_449_p3;
        p_Val2_7_reg_1609 <= p_Val2_7_fu_464_p3;
        r_V_5_reg_1694[48 : 0] <= r_V_5_fu_809_p1[48 : 0];
        result_V_reg_1805 <= {{grp_fu_1009_p2[125:63]}};
        ret_V_reg_1790 <= ret_V_fu_997_p2;
        select_ln272_1_reg_1785 <= select_ln272_1_fu_950_p3;
        shl_ln1253_1_reg_1855 <= shl_ln1253_1_fu_1189_p2;
        shl_ln1253_reg_1850 <= shl_ln1253_fu_1180_p2;
        tmp_3_reg_1775 <= {{r_V_25_fu_912_p2[74:38]}};
        tmp_4_reg_1780 <= {{r_V_26_fu_934_p2[59:31]}};
        tmp_V_reg_1542_pp0_iter2_reg <= tmp_V_reg_1542_pp0_iter1_reg;
        tmp_V_reg_1542_pp0_iter3_reg <= tmp_V_reg_1542_pp0_iter2_reg;
        tmp_i2_i_reg_1837 <= tmp_i2_i_fu_1150_p3;
        tmp_i4_i_reg_1843 <= tmp_i4_i_fu_1168_p3;
        tmp_i_i2_reg_1831 <= tmp_i_i2_fu_1132_p3;
        trunc_ln1_reg_1770 <= {{grp_fu_868_p2[107:52]}};
        trunc_ln662_1_reg_1755 <= {{r_V_24_fu_880_p2[92:45]}};
        trunc_ln662_1_reg_1755_pp0_iter8_reg <= trunc_ln662_1_reg_1755;
        zext_ln498_reg_1666[7 : 0] <= zext_ln498_fu_685_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        closepath_reg_1555 <= closepath_fu_334_p2;
        closepath_reg_1555_pp0_iter1_reg <= closepath_reg_1555;
        do_cos_read_reg_1529 <= do_cos;
        do_cos_read_reg_1529_pp0_iter1_reg <= do_cos_read_reg_1529;
        p_Result_s_reg_1536 <= p_Val2_s_fu_308_p1[32'd63];
        p_Result_s_reg_1536_pp0_iter1_reg <= p_Result_s_reg_1536;
        ret_V_14_reg_1571 <= {{r_V_17_fu_376_p2[255:86]}};
        tmp_V_1_reg_1549 <= tmp_V_1_fu_330_p1;
        tmp_V_1_reg_1549_pp0_iter1_reg <= tmp_V_1_reg_1549;
        tmp_V_reg_1542 <= {{p_Val2_s_fu_308_p1[62:52]}};
        tmp_V_reg_1542_pp0_iter1_reg <= tmp_V_reg_1542;
        trunc_ln601_reg_1566 <= trunc_ln601_fu_369_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (closepath_reg_1555_pp0_iter2_reg == 1'd0))) begin
        trunc_ln_i_reg_1598 <= {{grp_fu_406_p2[169:167]}};
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to12 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        fourth_order_double_4_ce0 = 1'b1;
    end else begin
        fourth_order_double_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        fourth_order_double_5_ce0 = 1'b1;
    end else begin
        fourth_order_double_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        fourth_order_double_6_ce0 = 1'b1;
    end else begin
        fourth_order_double_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        fourth_order_double_7_ce0 = 1'b1;
    end else begin
        fourth_order_double_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        fourth_order_double_s_ce0 = 1'b1;
    end else begin
        fourth_order_double_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_4oPi_table_256_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_256_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_V_fu_652_p1 = r_V_19_fu_601_p3[55:0];

assign Ex_V_fu_523_p2 = (select_ln482_fu_442_p3 - zext_ln655_fu_519_p1);

assign Mx_V_fu_555_p4 = {{r_V_18_fu_550_p2[123:61]}};

assign Mx_bits_V_1_fu_459_p2 = (124'd0 - p_Val2_36_reg_1592);

assign Mx_zeros_V_fu_515_p1 = tmp_i_i_fu_507_p3[5:0];

assign add_ln114_1_fu_340_p2 = ($signed(11'd1101) + $signed(tmp_V_fu_320_p4));

assign add_ln114_fu_437_p2 = ($signed(11'd1027) + $signed(tmp_V_reg_1542_pp0_iter3_reg));

assign add_ln442_1_fu_1262_p2 = (add_ln442_fu_1252_p2 + tmp_i4_i_reg_1843);

assign add_ln442_2_fu_1280_p2 = (add_ln442_1_fu_1262_p2 + tmp_i6_i_fu_1239_p3);

assign add_ln442_fu_1252_p2 = (32'd16 + tmp_i2_i_reg_1837);

assign add_ln452_fu_1349_p2 = ($signed(12'd1023) + $signed(rhs_V_fu_1206_p1));

assign addr_V_fu_346_p3 = ((closepath_fu_334_p2[0:0] === 1'b1) ? 11'd74 : add_ln114_1_fu_340_p2);

assign and_ln300_1_fu_1486_p2 = (icmp_ln833_reg_1631_pp0_iter12_reg & icmp_ln833_1_reg_1586_pp0_iter12_reg);

assign and_ln300_fu_781_p2 = (icmp_ln833_reg_1631 & icmp_ln833_1_reg_1586_pp0_iter4_reg);

assign and_ln307_fu_785_p2 = (xor_ln29_fu_666_p2 & p_Result_s_reg_1536_pp0_iter4_reg);

assign and_ln311_fu_795_p2 = (xor_ln311_fu_790_p2 & select_ln271_fu_773_p3);

assign and_ln444_1_fu_1308_p2 = (icmp_ln444_2_fu_1275_p2 & icmp_ln444_1_fu_1257_p2);

assign and_ln444_2_fu_1314_p2 = (icmp_ln444_fu_1247_p2 & and_ln444_1_fu_1308_p2);

assign and_ln444_fu_1302_p2 = (xor_ln444_fu_1296_p2 & icmp_ln444_fu_1247_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = p_Result_30_fu_1516_p4;

assign closepath_fu_334_p2 = ((tmp_V_fu_320_p4 < 11'd1022) ? 1'b1 : 1'b0);

assign cos_basis_fu_635_p3 = ((do_cos_read_reg_1529_pp0_iter4_reg[0:0] === 1'b1) ? xor_ln271_fu_629_p2 : tmp_1_fu_608_p10);

assign empty_fu_1378_p1 = newexp_fu_1359_p2[10:0];

assign fourth_order_double_4_address0 = zext_ln498_reg_1666;

assign fourth_order_double_5_address0 = zext_ln498_fu_685_p1;

assign fourth_order_double_6_address0 = zext_ln498_fu_685_p1;

assign fourth_order_double_7_address0 = zext_ln498_reg_1666;

assign fourth_order_double_s_address0 = zext_ln498_reg_1666;

assign grp_fu_1009_p1 = grp_fu_1009_p10;

assign grp_fu_1009_p10 = select_ln272_1_reg_1785;

assign grp_fu_406_p0 = grp_fu_406_p00;

assign grp_fu_406_p00 = ret_V_14_reg_1571;

assign grp_fu_406_p1 = grp_fu_406_p10;

assign grp_fu_406_p10 = p_Result_20_fu_392_p3;

assign grp_fu_868_p0 = grp_fu_868_p00;

assign grp_fu_868_p00 = B_V_reg_1656_pp0_iter6_reg;

assign icmp_ln1452_fu_1195_p2 = ((result_V_reg_1805 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln444_1_fu_1257_p2 = ((tmp_i2_i_reg_1837 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln444_2_fu_1275_p2 = ((tmp_i4_i_reg_1843 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln444_fu_1247_p2 = ((tmp_i_i2_reg_1831 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln833_1_fu_412_p2 = ((tmp_V_1_reg_1549_pp0_iter1_reg == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_2_fu_542_p2 = ((tmp_V_reg_1542_pp0_iter3_reg == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_537_p2 = ((tmp_V_reg_1542_pp0_iter3_reg == 11'd0) ? 1'b1 : 1'b0);

assign lhs_V_1_fu_963_p1 = $signed(t1_V_fu_956_p3);

assign newexp_fu_1359_p2 = ($signed(sext_ln452_fu_1355_p1) - $signed(select_ln444_2_fu_1341_p3));

assign or_ln300_fu_1504_p2 = (icmp_ln833_2_reg_1637_pp0_iter12_reg | and_ln300_reg_1683_pp0_iter12_reg);

assign or_ln311_fu_1466_p2 = (or_ln453_fu_1373_p2 | icmp_ln833_2_reg_1637_pp0_iter12_reg);

assign or_ln444_fu_1320_p2 = (and_ln444_fu_1302_p2 | and_ln444_2_fu_1314_p2);

assign or_ln453_fu_1373_p2 = (tmp_11_fu_1365_p3 | icmp_ln1452_reg_1861);

assign p_Repl2_2_fu_801_p3 = ((and_ln300_fu_781_p2[0:0] === 1'b1) ? and_ln307_fu_785_p2 : and_ln311_fu_795_p2);

assign p_Result_20_fu_392_p3 = {{1'd1}, {tmp_V_1_reg_1549_pp0_iter1_reg}};

assign p_Result_21_fu_481_p3 = {{p_Result_i_i_39_fu_471_p4}, {1'd1}};

assign p_Result_22_fu_499_p3 = {{2'd3}, {p_Result_8_fu_489_p4}};

assign p_Result_23_fu_677_p3 = {{sin_basis_fu_671_p2}, {p_Result_i_fu_642_p4}};

assign p_Result_24_fu_1217_p5 = {{tmp_6_i_fu_1210_p3}, {ap_const_lv32_0[15:0]}};

integer ap_tvar_int_0;

always @ (p_Val2_27_fu_1072_p5) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_25_fu_1122_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_25_fu_1122_p4[ap_tvar_int_0] = p_Val2_27_fu_1072_p5[31 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (p_Val2_28_fu_1091_p5) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            p_Result_26_fu_1140_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_26_fu_1140_p4[ap_tvar_int_1] = p_Val2_28_fu_1091_p5[31 - ap_tvar_int_1];
        end
    end
end

integer ap_tvar_int_2;

always @ (p_Val2_29_fu_1110_p5) begin
    for (ap_tvar_int_2 = 32 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 31 - 0) begin
            p_Result_27_fu_1158_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_27_fu_1158_p4[ap_tvar_int_2] = p_Val2_29_fu_1110_p5[31 - ap_tvar_int_2];
        end
    end
end

integer ap_tvar_int_3;

always @ (p_Result_24_fu_1217_p5) begin
    for (ap_tvar_int_3 = 32 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 31 - 0) begin
            p_Result_28_fu_1229_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            p_Result_28_fu_1229_p4[ap_tvar_int_3] = p_Result_24_fu_1217_p5[31 - ap_tvar_int_3];
        end
    end
end

assign p_Result_29_fu_691_p3 = {{p_Result_s_reg_1536_pp0_iter4_reg}, {p_Val2_37_reg_1603}};

assign p_Result_30_fu_1516_p4 = {{{p_Repl2_2_reg_1689_pp0_iter12_reg}, {ret_V_12_fu_1479_p3}}, {ret_V_13_fu_1508_p3}};

integer ap_tvar_int_4;

always @ (p_Result_21_fu_481_p3) begin
    for (ap_tvar_int_4 = 62 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 61 - 0) begin
            p_Result_8_fu_489_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            p_Result_8_fu_489_p4[ap_tvar_int_4] = p_Result_21_fu_481_p3[61 - ap_tvar_int_4];
        end
    end
end

assign p_Result_i_fu_642_p4 = {{r_V_19_fu_601_p3[62:56]}};

assign p_Result_i_i_39_fu_471_p4 = {{p_Val2_7_fu_464_p3[123:63]}};

assign p_Result_i_i_fu_354_p4 = {{addr_V_fu_346_p3[10:7]}};

assign p_Val2_27_fu_1072_p5 = {{tmp_i_fu_1065_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_28_fu_1091_p5 = {{tmp_4_i_fu_1084_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_29_fu_1110_p5 = {{tmp_5_i_fu_1103_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_37_fu_449_p3 = ((closepath_reg_1555_pp0_iter3_reg[0:0] === 1'b1) ? 3'd0 : trunc_ln_i_reg_1598);

assign p_Val2_7_fu_464_p3 = ((trunc_ln745_fu_455_p1[0:0] === 1'b1) ? Mx_bits_V_1_fu_459_p2 : p_Val2_36_reg_1592);

assign p_Val2_s_fu_308_p1 = t_in;

assign r_V_17_fu_376_p2 = ref_4oPi_table_256_V_q0 << zext_ln744_fu_373_p1;

assign r_V_18_fu_550_p2 = p_Val2_7_reg_1609 << zext_ln1253_fu_547_p1;

assign r_V_19_fu_601_p3 = ((isNeg_reg_1625[0:0] === 1'b1) ? r_V_fu_589_p2 : r_V_3_fu_595_p2);

assign r_V_20_fu_812_p0 = r_V_5_fu_809_p1;

assign r_V_20_fu_812_p1 = r_V_5_fu_809_p1;

assign r_V_20_fu_812_p2 = (r_V_20_fu_812_p0 * r_V_20_fu_812_p1);

assign r_V_21_fu_831_p0 = r_V_5_reg_1694;

assign r_V_21_fu_831_p1 = r_V_8_fu_828_p1;

assign r_V_21_fu_831_p2 = (r_V_21_fu_831_p0 * r_V_21_fu_831_p1);

assign r_V_22_fu_846_p0 = r_V_8_fu_828_p1;

assign r_V_22_fu_846_p1 = r_V_8_fu_828_p1;

assign r_V_22_fu_846_p2 = (r_V_22_fu_846_p0 * r_V_22_fu_846_p1);

assign r_V_24_fu_880_p0 = r_V_24_fu_880_p00;

assign r_V_24_fu_880_p00 = B_squared_V_reg_1699;

assign r_V_24_fu_880_p1 = fourth_order_double_12_reg_1715;

assign r_V_24_fu_880_p2 = ($signed({{1'b0}, {r_V_24_fu_880_p0}}) * $signed(r_V_24_fu_880_p1));

assign r_V_25_fu_912_p0 = r_V_25_fu_912_p00;

assign r_V_25_fu_912_p00 = B_third_power_V_reg_1730;

assign r_V_25_fu_912_p1 = r_V_25_fu_912_p10;

assign r_V_25_fu_912_p10 = fourth_order_double_14_reg_1760;

assign r_V_25_fu_912_p2 = (r_V_25_fu_912_p0 * r_V_25_fu_912_p1);

assign r_V_26_fu_934_p0 = r_V_26_fu_934_p00;

assign r_V_26_fu_934_p00 = B_fourth_power_V_reg_1735;

assign r_V_26_fu_934_p1 = r_V_26_fu_934_p10;

assign r_V_26_fu_934_p10 = fourth_order_double_16_reg_1765;

assign r_V_26_fu_934_p2 = (r_V_26_fu_934_p0 * r_V_26_fu_934_p1);

assign r_V_3_fu_595_p2 = Mx_V_fu_555_p4 << zext_ln1287_fu_585_p1;

assign r_V_5_fu_809_p1 = B_trunc_V_reg_1661;

assign r_V_8_fu_828_p1 = B_squared_V_reg_1699;

assign r_V_fu_589_p2 = Mx_V_fu_555_p4 >> zext_ln1287_fu_585_p1;

assign ref_4oPi_table_256_V_address0 = zext_ln635_fu_364_p1;

assign ret_V_12_fu_1479_p3 = ((and_ln300_reg_1683_pp0_iter12_reg[0:0] === 1'b1) ? select_ln307_fu_1452_p3 : select_ln311_fu_1471_p3);

assign ret_V_13_fu_1508_p3 = ((or_ln300_fu_1504_p2[0:0] === 1'b1) ? select_ln300_2_fu_1496_p3 : significand_V_fu_1444_p3);

assign ret_V_16_fu_970_p2 = ($signed(lhs_V_1_fu_963_p1) + $signed(rhs_V_2_fu_967_p1));

assign ret_V_17_fu_979_p2 = ($signed(ret_V_16_fu_970_p2) + $signed(sext_ln657_fu_976_p1));

assign ret_V_18_fu_988_p2 = (ret_V_17_fu_979_p2 + zext_ln657_fu_985_p1);

assign ret_V_fu_997_p2 = (ret_V_18_fu_988_p2 + zext_ln657_1_fu_994_p1);

assign rhs_V_2_fu_967_p1 = $signed(trunc_ln1_reg_1770);

assign rhs_V_fu_1206_p1 = $signed(select_ln272_fu_1200_p3);

assign select_ln271_fu_773_p3 = ((cos_basis_fu_635_p3[0:0] === 1'b1) ? tmp_fu_697_p18 : tmp_2_fu_735_p18);

assign select_ln272_1_fu_950_p3 = ((cos_basis_reg_1650_pp0_iter8_reg[0:0] === 1'b1) ? 63'd9223372036854775807 : Mx_V_reg_1645_pp0_iter8_reg);

assign select_ln272_fu_1200_p3 = ((cos_basis_reg_1650_pp0_iter12_reg[0:0] === 1'b1) ? 11'd0 : Ex_V_reg_1619_pp0_iter12_reg);

assign select_ln300_2_fu_1496_p3 = ((xor_ln300_fu_1490_p2[0:0] === 1'b1) ? 52'd4503599627370495 : 52'd0);

assign select_ln307_fu_1452_p3 = ((do_cos_read_reg_1529_pp0_iter12_reg[0:0] === 1'b1) ? 11'd1023 : 11'd0);

assign select_ln311_1_fu_1459_p3 = ((icmp_ln833_2_reg_1637_pp0_iter12_reg[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign select_ln311_fu_1471_p3 = ((or_ln311_fu_1466_p2[0:0] === 1'b1) ? select_ln311_1_fu_1459_p3 : empty_fu_1378_p1);

assign select_ln444_1_fu_1334_p3 = ((icmp_ln444_fu_1247_p2[0:0] === 1'b1) ? add_ln442_1_fu_1262_p2 : tmp_i_i2_reg_1831);

assign select_ln444_2_fu_1341_p3 = ((or_ln444_fu_1320_p2[0:0] === 1'b1) ? select_ln444_fu_1326_p3 : select_ln444_1_fu_1334_p3);

assign select_ln444_3_fu_1401_p3 = ((and_ln444_2_fu_1314_p2[0:0] === 1'b1) ? tmp_5_fu_1382_p4 : tmp_6_fu_1392_p4);

assign select_ln444_4_fu_1428_p3 = ((icmp_ln444_fu_1247_p2[0:0] === 1'b1) ? tmp_7_fu_1409_p4 : tmp_8_fu_1419_p4);

assign select_ln444_5_fu_1436_p3 = ((or_ln444_fu_1320_p2[0:0] === 1'b1) ? select_ln444_3_fu_1401_p3 : select_ln444_4_fu_1428_p3);

assign select_ln444_fu_1326_p3 = ((and_ln444_2_fu_1314_p2[0:0] === 1'b1) ? add_ln442_2_fu_1280_p2 : add_ln442_fu_1252_p2);

assign select_ln482_fu_442_p3 = ((closepath_reg_1555_pp0_iter3_reg[0:0] === 1'b1) ? add_ln114_fu_437_p2 : 11'd0);

assign sext_ln1311_fu_581_p1 = $signed(ush_fu_574_p3);

assign sext_ln1334_fu_565_p1 = Ex_V_reg_1619;

assign sext_ln452_fu_1355_p1 = $signed(add_ln452_fu_1349_p2);

assign sext_ln657_fu_976_p1 = $signed(trunc_ln662_1_reg_1755_pp0_iter8_reg);

assign shl_ln1253_1_fu_1189_p2 = shl_ln1253_fu_1180_p2 << zext_ln1287_2_fu_1185_p1;

assign shl_ln1253_2_fu_1270_p2 = shl_ln1253_1_reg_1855 << zext_ln1287_3_fu_1267_p1;

assign shl_ln1253_3_fu_1290_p2 = shl_ln1253_2_fu_1270_p2 << zext_ln1287_4_fu_1286_p1;

assign shl_ln1253_fu_1180_p2 = result_V_reg_1805 << zext_ln1287_1_fu_1176_p1;

assign significand_V_fu_1444_p3 = ((or_ln453_fu_1373_p2[0:0] === 1'b1) ? 52'd0 : select_ln444_5_fu_1436_p3);

assign sin_basis_fu_671_p2 = (xor_ln29_fu_666_p2 ^ tmp_1_fu_608_p10);

assign sub_ln1311_fu_568_p2 = ($signed(12'd0) - $signed(sext_ln1334_fu_565_p1));

assign t1_V_fu_956_p3 = {{p_Val2_15_reg_1740_pp0_iter8_reg}, {4'd0}};

assign tmp_11_fu_1365_p3 = newexp_fu_1359_p2[32'd31];

assign tmp_4_i_fu_1084_p3 = {{p_Result_13_1_i_reg_1816}, {1'd1}};

assign tmp_5_fu_1382_p4 = {{shl_ln1253_3_fu_1290_p2[61:10]}};

assign tmp_5_i_fu_1103_p3 = {{p_Result_13_2_i_reg_1821}, {1'd1}};

assign tmp_6_fu_1392_p4 = {{shl_ln1253_1_reg_1855[61:10]}};

assign tmp_6_i_fu_1210_p3 = {{p_Result_i_40_reg_1826_pp0_iter12_reg}, {1'd1}};

assign tmp_7_fu_1409_p4 = {{shl_ln1253_2_fu_1270_p2[61:10]}};

assign tmp_8_fu_1419_p4 = {{shl_ln1253_reg_1850[61:10]}};

assign tmp_V_1_fu_330_p1 = p_Val2_s_fu_308_p1[51:0];

assign tmp_V_fu_320_p4 = {{p_Val2_s_fu_308_p1[62:52]}};


always @ (p_Result_26_fu_1140_p4) begin
    if (p_Result_26_fu_1140_p4[0] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd0;
    end else if (p_Result_26_fu_1140_p4[1] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd1;
    end else if (p_Result_26_fu_1140_p4[2] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd2;
    end else if (p_Result_26_fu_1140_p4[3] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd3;
    end else if (p_Result_26_fu_1140_p4[4] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd4;
    end else if (p_Result_26_fu_1140_p4[5] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd5;
    end else if (p_Result_26_fu_1140_p4[6] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd6;
    end else if (p_Result_26_fu_1140_p4[7] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd7;
    end else if (p_Result_26_fu_1140_p4[8] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd8;
    end else if (p_Result_26_fu_1140_p4[9] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd9;
    end else if (p_Result_26_fu_1140_p4[10] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd10;
    end else if (p_Result_26_fu_1140_p4[11] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd11;
    end else if (p_Result_26_fu_1140_p4[12] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd12;
    end else if (p_Result_26_fu_1140_p4[13] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd13;
    end else if (p_Result_26_fu_1140_p4[14] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd14;
    end else if (p_Result_26_fu_1140_p4[15] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd15;
    end else if (p_Result_26_fu_1140_p4[16] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd16;
    end else if (p_Result_26_fu_1140_p4[17] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd17;
    end else if (p_Result_26_fu_1140_p4[18] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd18;
    end else if (p_Result_26_fu_1140_p4[19] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd19;
    end else if (p_Result_26_fu_1140_p4[20] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd20;
    end else if (p_Result_26_fu_1140_p4[21] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd21;
    end else if (p_Result_26_fu_1140_p4[22] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd22;
    end else if (p_Result_26_fu_1140_p4[23] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd23;
    end else if (p_Result_26_fu_1140_p4[24] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd24;
    end else if (p_Result_26_fu_1140_p4[25] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd25;
    end else if (p_Result_26_fu_1140_p4[26] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd26;
    end else if (p_Result_26_fu_1140_p4[27] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd27;
    end else if (p_Result_26_fu_1140_p4[28] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd28;
    end else if (p_Result_26_fu_1140_p4[29] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd29;
    end else if (p_Result_26_fu_1140_p4[30] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd30;
    end else if (p_Result_26_fu_1140_p4[31] == 1'b1) begin
        tmp_i2_i_fu_1150_p3 = 32'd31;
    end else begin
        tmp_i2_i_fu_1150_p3 = 32'd32;
    end
end


always @ (p_Result_27_fu_1158_p4) begin
    if (p_Result_27_fu_1158_p4[0] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd0;
    end else if (p_Result_27_fu_1158_p4[1] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd1;
    end else if (p_Result_27_fu_1158_p4[2] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd2;
    end else if (p_Result_27_fu_1158_p4[3] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd3;
    end else if (p_Result_27_fu_1158_p4[4] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd4;
    end else if (p_Result_27_fu_1158_p4[5] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd5;
    end else if (p_Result_27_fu_1158_p4[6] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd6;
    end else if (p_Result_27_fu_1158_p4[7] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd7;
    end else if (p_Result_27_fu_1158_p4[8] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd8;
    end else if (p_Result_27_fu_1158_p4[9] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd9;
    end else if (p_Result_27_fu_1158_p4[10] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd10;
    end else if (p_Result_27_fu_1158_p4[11] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd11;
    end else if (p_Result_27_fu_1158_p4[12] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd12;
    end else if (p_Result_27_fu_1158_p4[13] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd13;
    end else if (p_Result_27_fu_1158_p4[14] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd14;
    end else if (p_Result_27_fu_1158_p4[15] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd15;
    end else if (p_Result_27_fu_1158_p4[16] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd16;
    end else if (p_Result_27_fu_1158_p4[17] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd17;
    end else if (p_Result_27_fu_1158_p4[18] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd18;
    end else if (p_Result_27_fu_1158_p4[19] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd19;
    end else if (p_Result_27_fu_1158_p4[20] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd20;
    end else if (p_Result_27_fu_1158_p4[21] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd21;
    end else if (p_Result_27_fu_1158_p4[22] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd22;
    end else if (p_Result_27_fu_1158_p4[23] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd23;
    end else if (p_Result_27_fu_1158_p4[24] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd24;
    end else if (p_Result_27_fu_1158_p4[25] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd25;
    end else if (p_Result_27_fu_1158_p4[26] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd26;
    end else if (p_Result_27_fu_1158_p4[27] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd27;
    end else if (p_Result_27_fu_1158_p4[28] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd28;
    end else if (p_Result_27_fu_1158_p4[29] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd29;
    end else if (p_Result_27_fu_1158_p4[30] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd30;
    end else if (p_Result_27_fu_1158_p4[31] == 1'b1) begin
        tmp_i4_i_fu_1168_p3 = 32'd31;
    end else begin
        tmp_i4_i_fu_1168_p3 = 32'd32;
    end
end


always @ (p_Result_28_fu_1229_p4) begin
    if (p_Result_28_fu_1229_p4[0] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd0;
    end else if (p_Result_28_fu_1229_p4[1] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd1;
    end else if (p_Result_28_fu_1229_p4[2] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd2;
    end else if (p_Result_28_fu_1229_p4[3] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd3;
    end else if (p_Result_28_fu_1229_p4[4] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd4;
    end else if (p_Result_28_fu_1229_p4[5] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd5;
    end else if (p_Result_28_fu_1229_p4[6] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd6;
    end else if (p_Result_28_fu_1229_p4[7] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd7;
    end else if (p_Result_28_fu_1229_p4[8] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd8;
    end else if (p_Result_28_fu_1229_p4[9] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd9;
    end else if (p_Result_28_fu_1229_p4[10] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd10;
    end else if (p_Result_28_fu_1229_p4[11] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd11;
    end else if (p_Result_28_fu_1229_p4[12] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd12;
    end else if (p_Result_28_fu_1229_p4[13] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd13;
    end else if (p_Result_28_fu_1229_p4[14] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd14;
    end else if (p_Result_28_fu_1229_p4[15] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd15;
    end else if (p_Result_28_fu_1229_p4[16] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd16;
    end else if (p_Result_28_fu_1229_p4[17] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd17;
    end else if (p_Result_28_fu_1229_p4[18] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd18;
    end else if (p_Result_28_fu_1229_p4[19] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd19;
    end else if (p_Result_28_fu_1229_p4[20] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd20;
    end else if (p_Result_28_fu_1229_p4[21] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd21;
    end else if (p_Result_28_fu_1229_p4[22] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd22;
    end else if (p_Result_28_fu_1229_p4[23] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd23;
    end else if (p_Result_28_fu_1229_p4[24] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd24;
    end else if (p_Result_28_fu_1229_p4[25] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd25;
    end else if (p_Result_28_fu_1229_p4[26] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd26;
    end else if (p_Result_28_fu_1229_p4[27] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd27;
    end else if (p_Result_28_fu_1229_p4[28] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd28;
    end else if (p_Result_28_fu_1229_p4[29] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd29;
    end else if (p_Result_28_fu_1229_p4[30] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd30;
    end else if (p_Result_28_fu_1229_p4[31] == 1'b1) begin
        tmp_i6_i_fu_1239_p3 = 32'd31;
    end else begin
        tmp_i6_i_fu_1239_p3 = 32'd32;
    end
end

assign tmp_i_fu_1065_p3 = {{p_Result_1_i_reg_1811}, {1'd1}};


always @ (p_Result_25_fu_1122_p4) begin
    if (p_Result_25_fu_1122_p4[0] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd0;
    end else if (p_Result_25_fu_1122_p4[1] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd1;
    end else if (p_Result_25_fu_1122_p4[2] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd2;
    end else if (p_Result_25_fu_1122_p4[3] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd3;
    end else if (p_Result_25_fu_1122_p4[4] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd4;
    end else if (p_Result_25_fu_1122_p4[5] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd5;
    end else if (p_Result_25_fu_1122_p4[6] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd6;
    end else if (p_Result_25_fu_1122_p4[7] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd7;
    end else if (p_Result_25_fu_1122_p4[8] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd8;
    end else if (p_Result_25_fu_1122_p4[9] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd9;
    end else if (p_Result_25_fu_1122_p4[10] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd10;
    end else if (p_Result_25_fu_1122_p4[11] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd11;
    end else if (p_Result_25_fu_1122_p4[12] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd12;
    end else if (p_Result_25_fu_1122_p4[13] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd13;
    end else if (p_Result_25_fu_1122_p4[14] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd14;
    end else if (p_Result_25_fu_1122_p4[15] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd15;
    end else if (p_Result_25_fu_1122_p4[16] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd16;
    end else if (p_Result_25_fu_1122_p4[17] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd17;
    end else if (p_Result_25_fu_1122_p4[18] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd18;
    end else if (p_Result_25_fu_1122_p4[19] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd19;
    end else if (p_Result_25_fu_1122_p4[20] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd20;
    end else if (p_Result_25_fu_1122_p4[21] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd21;
    end else if (p_Result_25_fu_1122_p4[22] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd22;
    end else if (p_Result_25_fu_1122_p4[23] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd23;
    end else if (p_Result_25_fu_1122_p4[24] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd24;
    end else if (p_Result_25_fu_1122_p4[25] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd25;
    end else if (p_Result_25_fu_1122_p4[26] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd26;
    end else if (p_Result_25_fu_1122_p4[27] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd27;
    end else if (p_Result_25_fu_1122_p4[28] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd28;
    end else if (p_Result_25_fu_1122_p4[29] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd29;
    end else if (p_Result_25_fu_1122_p4[30] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd30;
    end else if (p_Result_25_fu_1122_p4[31] == 1'b1) begin
        tmp_i_i2_fu_1132_p3 = 32'd31;
    end else begin
        tmp_i_i2_fu_1132_p3 = 32'd32;
    end
end


always @ (p_Result_22_fu_499_p3) begin
    if (p_Result_22_fu_499_p3[0] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd0;
    end else if (p_Result_22_fu_499_p3[1] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd1;
    end else if (p_Result_22_fu_499_p3[2] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd2;
    end else if (p_Result_22_fu_499_p3[3] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd3;
    end else if (p_Result_22_fu_499_p3[4] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd4;
    end else if (p_Result_22_fu_499_p3[5] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd5;
    end else if (p_Result_22_fu_499_p3[6] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd6;
    end else if (p_Result_22_fu_499_p3[7] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd7;
    end else if (p_Result_22_fu_499_p3[8] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd8;
    end else if (p_Result_22_fu_499_p3[9] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd9;
    end else if (p_Result_22_fu_499_p3[10] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd10;
    end else if (p_Result_22_fu_499_p3[11] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd11;
    end else if (p_Result_22_fu_499_p3[12] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd12;
    end else if (p_Result_22_fu_499_p3[13] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd13;
    end else if (p_Result_22_fu_499_p3[14] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd14;
    end else if (p_Result_22_fu_499_p3[15] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd15;
    end else if (p_Result_22_fu_499_p3[16] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd16;
    end else if (p_Result_22_fu_499_p3[17] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd17;
    end else if (p_Result_22_fu_499_p3[18] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd18;
    end else if (p_Result_22_fu_499_p3[19] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd19;
    end else if (p_Result_22_fu_499_p3[20] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd20;
    end else if (p_Result_22_fu_499_p3[21] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd21;
    end else if (p_Result_22_fu_499_p3[22] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd22;
    end else if (p_Result_22_fu_499_p3[23] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd23;
    end else if (p_Result_22_fu_499_p3[24] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd24;
    end else if (p_Result_22_fu_499_p3[25] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd25;
    end else if (p_Result_22_fu_499_p3[26] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd26;
    end else if (p_Result_22_fu_499_p3[27] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd27;
    end else if (p_Result_22_fu_499_p3[28] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd28;
    end else if (p_Result_22_fu_499_p3[29] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd29;
    end else if (p_Result_22_fu_499_p3[30] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd30;
    end else if (p_Result_22_fu_499_p3[31] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd31;
    end else if (p_Result_22_fu_499_p3[32] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd32;
    end else if (p_Result_22_fu_499_p3[33] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd33;
    end else if (p_Result_22_fu_499_p3[34] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd34;
    end else if (p_Result_22_fu_499_p3[35] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd35;
    end else if (p_Result_22_fu_499_p3[36] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd36;
    end else if (p_Result_22_fu_499_p3[37] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd37;
    end else if (p_Result_22_fu_499_p3[38] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd38;
    end else if (p_Result_22_fu_499_p3[39] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd39;
    end else if (p_Result_22_fu_499_p3[40] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd40;
    end else if (p_Result_22_fu_499_p3[41] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd41;
    end else if (p_Result_22_fu_499_p3[42] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd42;
    end else if (p_Result_22_fu_499_p3[43] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd43;
    end else if (p_Result_22_fu_499_p3[44] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd44;
    end else if (p_Result_22_fu_499_p3[45] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd45;
    end else if (p_Result_22_fu_499_p3[46] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd46;
    end else if (p_Result_22_fu_499_p3[47] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd47;
    end else if (p_Result_22_fu_499_p3[48] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd48;
    end else if (p_Result_22_fu_499_p3[49] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd49;
    end else if (p_Result_22_fu_499_p3[50] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd50;
    end else if (p_Result_22_fu_499_p3[51] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd51;
    end else if (p_Result_22_fu_499_p3[52] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd52;
    end else if (p_Result_22_fu_499_p3[53] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd53;
    end else if (p_Result_22_fu_499_p3[54] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd54;
    end else if (p_Result_22_fu_499_p3[55] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd55;
    end else if (p_Result_22_fu_499_p3[56] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd56;
    end else if (p_Result_22_fu_499_p3[57] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd57;
    end else if (p_Result_22_fu_499_p3[58] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd58;
    end else if (p_Result_22_fu_499_p3[59] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd59;
    end else if (p_Result_22_fu_499_p3[60] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd60;
    end else if (p_Result_22_fu_499_p3[61] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd61;
    end else if (p_Result_22_fu_499_p3[62] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd62;
    end else if (p_Result_22_fu_499_p3[63] == 1'b1) begin
        tmp_i_i_fu_507_p3 = 64'd63;
    end else begin
        tmp_i_i_fu_507_p3 = 64'd64;
    end
end

assign trunc_ln601_fu_369_p1 = addr_V_fu_346_p3[6:0];

assign trunc_ln745_fu_455_p1 = p_Val2_37_fu_449_p3[0:0];

assign ush_fu_574_p3 = ((isNeg_reg_1625[0:0] === 1'b1) ? sub_ln1311_fu_568_p2 : sext_ln1334_fu_565_p1);

assign xor_ln271_fu_629_p2 = (tmp_1_fu_608_p10 ^ 1'd1);

assign xor_ln29_fu_666_p2 = (do_cos_read_reg_1529_pp0_iter4_reg ^ 1'd1);

assign xor_ln300_fu_1490_p2 = (1'd1 ^ and_ln300_1_fu_1486_p2);

assign xor_ln311_fu_790_p2 = (icmp_ln833_2_reg_1637 ^ 1'd1);

assign xor_ln444_fu_1296_p2 = (icmp_ln444_1_fu_1257_p2 ^ 1'd1);

assign zext_ln1253_fu_547_p1 = Mx_zeros_V_reg_1614;

assign zext_ln1287_1_fu_1176_p1 = tmp_i_i2_fu_1132_p3;

assign zext_ln1287_2_fu_1185_p1 = tmp_i2_i_fu_1150_p3;

assign zext_ln1287_3_fu_1267_p1 = tmp_i4_i_reg_1843;

assign zext_ln1287_4_fu_1286_p1 = tmp_i6_i_fu_1239_p3;

assign zext_ln1287_fu_585_p1 = $unsigned(sext_ln1311_fu_581_p1);

assign zext_ln498_fu_685_p1 = p_Result_23_fu_677_p3;

assign zext_ln635_fu_364_p1 = p_Result_i_i_fu_354_p4;

assign zext_ln655_fu_519_p1 = Mx_zeros_V_fu_515_p1;

assign zext_ln657_1_fu_994_p1 = tmp_4_reg_1780;

assign zext_ln657_fu_985_p1 = tmp_3_reg_1775;

assign zext_ln744_fu_373_p1 = trunc_ln601_reg_1566;

always @ (posedge ap_clk) begin
    zext_ln498_reg_1666[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    r_V_5_reg_1694[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //sin_or_cos_double_s
