// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fft_stage_179.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fft_stage_179::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fft_stage_179::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> fft_stage_179::ap_ST_fsm_state1 = "1";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state2 = "10";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state3 = "100";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state4 = "1000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state5 = "10000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state6 = "100000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state7 = "1000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state8 = "10000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state9 = "100000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state10 = "1000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state11 = "10000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state12 = "100000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<21> fft_stage_179::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> fft_stage_179::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool fft_stage_179::ap_const_boolean_1 = true;
const sc_lv<32> fft_stage_179::ap_const_lv32_8 = "1000";
const sc_lv<32> fft_stage_179::ap_const_lv32_F = "1111";
const sc_lv<32> fft_stage_179::ap_const_lv32_13 = "10011";
const sc_lv<32> fft_stage_179::ap_const_lv32_1 = "1";
const sc_lv<32> fft_stage_179::ap_const_lv32_2 = "10";
const sc_lv<32> fft_stage_179::ap_const_lv32_4 = "100";
const bool fft_stage_179::ap_const_boolean_0 = false;
const sc_lv<32> fft_stage_179::ap_const_lv32_6 = "110";
const sc_lv<32> fft_stage_179::ap_const_lv32_7 = "111";
const sc_lv<1> fft_stage_179::ap_const_lv1_1 = "1";
const sc_lv<32> fft_stage_179::ap_const_lv32_B = "1011";
const sc_lv<32> fft_stage_179::ap_const_lv32_E = "1110";
const sc_lv<1> fft_stage_179::ap_const_lv1_0 = "0";
const sc_lv<3> fft_stage_179::ap_const_lv3_0 = "000";
const sc_lv<32> fft_stage_179::ap_const_lv32_14 = "10100";
const sc_lv<32> fft_stage_179::ap_const_lv32_3 = "11";
const sc_lv<32> fft_stage_179::ap_const_lv32_BF490FDB = "10111111010010010000111111011011";
const sc_lv<32> fft_stage_179::ap_const_lv32_C = "1100";
const sc_lv<32> fft_stage_179::ap_const_lv32_10 = "10000";
const sc_lv<32> fft_stage_179::ap_const_lv32_9 = "1001";
const sc_lv<32> fft_stage_179::ap_const_lv32_5 = "101";
const sc_lv<3> fft_stage_179::ap_const_lv3_4 = "100";
const sc_lv<3> fft_stage_179::ap_const_lv3_1 = "1";
const sc_lv<32> fft_stage_179::ap_const_lv32_A = "1010";
const sc_lv<32> fft_stage_179::ap_const_lv32_1F = "11111";
const sc_lv<22> fft_stage_179::ap_const_lv22_1 = "1";
const sc_lv<2> fft_stage_179::ap_const_lv2_0 = "00";
const sc_lv<2> fft_stage_179::ap_const_lv2_1 = "1";

fft_stage_179::fft_stage_179(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_sin_or_cos_double_s_fu_189 = new sin_or_cos_double_s("grp_sin_or_cos_double_s_fu_189");
    grp_sin_or_cos_double_s_fu_189->ap_clk(ap_clk);
    grp_sin_or_cos_double_s_fu_189->ap_rst(ap_rst);
    grp_sin_or_cos_double_s_fu_189->ap_start(grp_sin_or_cos_double_s_fu_189_ap_start);
    grp_sin_or_cos_double_s_fu_189->ap_done(grp_sin_or_cos_double_s_fu_189_ap_done);
    grp_sin_or_cos_double_s_fu_189->ap_idle(grp_sin_or_cos_double_s_fu_189_ap_idle);
    grp_sin_or_cos_double_s_fu_189->ap_ready(grp_sin_or_cos_double_s_fu_189_ap_ready);
    grp_sin_or_cos_double_s_fu_189->t_in(x_assign_reg_365);
    grp_sin_or_cos_double_s_fu_189->do_cos(grp_sin_or_cos_double_s_fu_189_do_cos);
    grp_sin_or_cos_double_s_fu_189->ap_return(grp_sin_or_cos_double_s_fu_189_ap_return);
    grp_sin_or_cos_double_s_fu_208 = new sin_or_cos_double_s("grp_sin_or_cos_double_s_fu_208");
    grp_sin_or_cos_double_s_fu_208->ap_clk(ap_clk);
    grp_sin_or_cos_double_s_fu_208->ap_rst(ap_rst);
    grp_sin_or_cos_double_s_fu_208->ap_start(grp_sin_or_cos_double_s_fu_208_ap_start);
    grp_sin_or_cos_double_s_fu_208->ap_done(grp_sin_or_cos_double_s_fu_208_ap_done);
    grp_sin_or_cos_double_s_fu_208->ap_idle(grp_sin_or_cos_double_s_fu_208_ap_idle);
    grp_sin_or_cos_double_s_fu_208->ap_ready(grp_sin_or_cos_double_s_fu_208_ap_ready);
    grp_sin_or_cos_double_s_fu_208->t_in(x_assign_reg_365);
    grp_sin_or_cos_double_s_fu_208->do_cos(grp_sin_or_cos_double_s_fu_208_do_cos);
    grp_sin_or_cos_double_s_fu_208->ap_return(grp_sin_or_cos_double_s_fu_208_ap_return);
    fft_faddfsub_32nslbW_U62 = new fft_faddfsub_32nslbW<1,4,32,32,32>("fft_faddfsub_32nslbW_U62");
    fft_faddfsub_32nslbW_U62->clk(ap_clk);
    fft_faddfsub_32nslbW_U62->reset(ap_rst);
    fft_faddfsub_32nslbW_U62->din0(grp_fu_227_p0);
    fft_faddfsub_32nslbW_U62->din1(grp_fu_227_p1);
    fft_faddfsub_32nslbW_U62->opcode(grp_fu_227_opcode);
    fft_faddfsub_32nslbW_U62->ce(grp_fu_227_ce);
    fft_faddfsub_32nslbW_U62->dout(grp_fu_227_p2);
    fft_faddfsub_32nslbW_U63 = new fft_faddfsub_32nslbW<1,4,32,32,32>("fft_faddfsub_32nslbW_U63");
    fft_faddfsub_32nslbW_U63->clk(ap_clk);
    fft_faddfsub_32nslbW_U63->reset(ap_rst);
    fft_faddfsub_32nslbW_U63->din0(grp_fu_233_p0);
    fft_faddfsub_32nslbW_U63->din1(grp_fu_233_p1);
    fft_faddfsub_32nslbW_U63->opcode(grp_fu_233_opcode);
    fft_faddfsub_32nslbW_U63->ce(ap_var_for_const0);
    fft_faddfsub_32nslbW_U63->dout(grp_fu_233_p2);
    fft_fadd_32ns_32nmb6_U64 = new fft_fadd_32ns_32nmb6<1,4,32,32,32>("fft_fadd_32ns_32nmb6_U64");
    fft_fadd_32ns_32nmb6_U64->clk(ap_clk);
    fft_fadd_32ns_32nmb6_U64->reset(ap_rst);
    fft_fadd_32ns_32nmb6_U64->din0(reg_267);
    fft_fadd_32ns_32nmb6_U64->din1(reg_282);
    fft_fadd_32ns_32nmb6_U64->ce(ap_var_for_const0);
    fft_fadd_32ns_32nmb6_U64->dout(grp_fu_237_p2);
    fft_fadd_32ns_32nmb6_U65 = new fft_fadd_32ns_32nmb6<1,4,32,32,32>("fft_fadd_32ns_32nmb6_U65");
    fft_fadd_32ns_32nmb6_U65->clk(ap_clk);
    fft_fadd_32ns_32nmb6_U65->reset(ap_rst);
    fft_fadd_32ns_32nmb6_U65->din0(reg_274);
    fft_fadd_32ns_32nmb6_U65->din1(reg_289);
    fft_fadd_32ns_32nmb6_U65->ce(ap_var_for_const0);
    fft_fadd_32ns_32nmb6_U65->dout(grp_fu_241_p2);
    fft_fmul_32ns_32nncg_U66 = new fft_fmul_32ns_32nncg<1,3,32,32,32>("fft_fmul_32ns_32nncg_U66");
    fft_fmul_32ns_32nncg_U66->clk(ap_clk);
    fft_fmul_32ns_32nncg_U66->reset(ap_rst);
    fft_fmul_32ns_32nncg_U66->din0(reg_267);
    fft_fmul_32ns_32nncg_U66->din1(c_reg_386);
    fft_fmul_32ns_32nncg_U66->ce(ap_var_for_const0);
    fft_fmul_32ns_32nncg_U66->dout(grp_fu_245_p2);
    fft_fmul_32ns_32nncg_U67 = new fft_fmul_32ns_32nncg<1,3,32,32,32>("fft_fmul_32ns_32nncg_U67");
    fft_fmul_32ns_32nncg_U67->clk(ap_clk);
    fft_fmul_32ns_32nncg_U67->reset(ap_rst);
    fft_fmul_32ns_32nncg_U67->din0(reg_274);
    fft_fmul_32ns_32nncg_U67->din1(s_reg_392);
    fft_fmul_32ns_32nncg_U67->ce(ap_var_for_const0);
    fft_fmul_32ns_32nncg_U67->dout(grp_fu_249_p2);
    fft_fmul_32ns_32nncg_U68 = new fft_fmul_32ns_32nncg<1,3,32,32,32>("fft_fmul_32ns_32nncg_U68");
    fft_fmul_32ns_32nncg_U68->clk(ap_clk);
    fft_fmul_32ns_32nncg_U68->reset(ap_rst);
    fft_fmul_32ns_32nncg_U68->din0(reg_274);
    fft_fmul_32ns_32nncg_U68->din1(c_reg_386);
    fft_fmul_32ns_32nncg_U68->ce(ap_var_for_const0);
    fft_fmul_32ns_32nncg_U68->dout(grp_fu_253_p2);
    fft_fptrunc_64ns_ocq_U69 = new fft_fptrunc_64ns_ocq<1,2,64,32>("fft_fptrunc_64ns_ocq_U69");
    fft_fptrunc_64ns_ocq_U69->clk(ap_clk);
    fft_fptrunc_64ns_ocq_U69->reset(ap_rst);
    fft_fptrunc_64ns_ocq_U69->din0(tmp_i_i_reg_371);
    fft_fptrunc_64ns_ocq_U69->ce(ap_var_for_const0);
    fft_fptrunc_64ns_ocq_U69->dout(grp_fu_257_p1);
    fft_fptrunc_64ns_ocq_U70 = new fft_fptrunc_64ns_ocq<1,2,64,32>("fft_fptrunc_64ns_ocq_U70");
    fft_fptrunc_64ns_ocq_U70->clk(ap_clk);
    fft_fptrunc_64ns_ocq_U70->reset(ap_rst);
    fft_fptrunc_64ns_ocq_U70->din0(tmp_i_i1_reg_376);
    fft_fptrunc_64ns_ocq_U70->ce(ap_var_for_const0);
    fft_fptrunc_64ns_ocq_U70->dout(grp_fu_260_p1);
    fft_fpext_32ns_64pcA_U71 = new fft_fpext_32ns_64pcA<1,2,32,64>("fft_fpext_32ns_64pcA_U71");
    fft_fpext_32ns_64pcA_U71->clk(ap_clk);
    fft_fpext_32ns_64pcA_U71->reset(ap_rst);
    fft_fpext_32ns_64pcA_U71->din0(a_0_reg_156);
    fft_fpext_32ns_64pcA_U71->ce(ap_var_for_const0);
    fft_fpext_32ns_64pcA_U71->dout(grp_fu_263_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Out_I_3_address0);
    sensitive << ( sext_ln48_reg_400 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_address1);
    sensitive << ( sext_ln50_reg_432 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_ce0);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_ce1);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_d0);
    sensitive << ( reg_289 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_d1);
    sensitive << ( tmp_4_reg_458 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_we0);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_I_3_we1);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_address0);
    sensitive << ( sext_ln48_reg_400 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_address1);
    sensitive << ( sext_ln50_reg_432 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_ce0);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_ce1);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_d0);
    sensitive << ( reg_282 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_d1);
    sensitive << ( tmp_6_reg_453 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_we0);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Out_R_3_we1);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_X_I_2_address0);
    sensitive << ( sext_ln48_fu_334_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( sext_ln50_fu_340_p1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_X_I_2_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_X_R_2_address0);
    sensitive << ( sext_ln48_fu_334_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( sext_ln50_fu_340_p1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_X_R_2_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state5_on_subcall_done);
    sensitive << ( grp_sin_or_cos_double_s_fu_189_ap_done );
    sensitive << ( grp_sin_or_cos_double_s_fu_208_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln39_fu_300_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln39_fu_300_p2 );

    SC_METHOD(thread_grp_fu_227_ce);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_state5_on_subcall_done );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_fu_227_opcode);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( icmp_ln39_fu_300_p2 );

    SC_METHOD(thread_grp_fu_227_p0);
    sensitive << ( reg_267 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_7_reg_416 );
    sensitive << ( a_0_reg_156 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_227_p1);
    sensitive << ( reg_282 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_reg_421 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_233_opcode);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_233_p0);
    sensitive << ( reg_274 );
    sensitive << ( tmp_9_reg_427 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_233_p1);
    sensitive << ( reg_289 );
    sensitive << ( tmp_8_reg_421 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_189_ap_start);
    sensitive << ( grp_sin_or_cos_double_s_fu_189_ap_start_reg );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_189_do_cos);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_208_ap_start);
    sensitive << ( grp_sin_or_cos_double_s_fu_208_ap_start_reg );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_208_do_cos);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_i_10_fu_346_p2);
    sensitive << ( i_0_reg_179 );

    SC_METHOD(thread_i_lower_fu_328_p2);
    sensitive << ( i_0_reg_179 );

    SC_METHOD(thread_icmp_ln39_fu_300_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_168 );

    SC_METHOD(thread_icmp_ln46_fu_322_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_18_fu_312_p4 );

    SC_METHOD(thread_j_fu_306_p2);
    sensitive << ( i_reg_168 );

    SC_METHOD(thread_sext_ln48_fu_334_p1);
    sensitive << ( i_lower_fu_328_p2 );

    SC_METHOD(thread_sext_ln50_fu_340_p1);
    sensitive << ( i_0_reg_179 );

    SC_METHOD(thread_tmp_18_fu_312_p4);
    sensitive << ( i_0_reg_179 );

    SC_METHOD(thread_zext_ln39_fu_296_p1);
    sensitive << ( i_reg_168 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_state5_on_subcall_done );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln46_fu_322_p2 );
    sensitive << ( icmp_ln39_fu_300_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000000000000001";
    grp_sin_or_cos_double_s_fu_189_ap_start_reg = SC_LOGIC_0;
    grp_sin_or_cos_double_s_fu_208_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fft_stage_179_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_R_2_address0, "(port)X_R_2_address0");
    sc_trace(mVcdFile, X_R_2_ce0, "(port)X_R_2_ce0");
    sc_trace(mVcdFile, X_R_2_q0, "(port)X_R_2_q0");
    sc_trace(mVcdFile, X_I_2_address0, "(port)X_I_2_address0");
    sc_trace(mVcdFile, X_I_2_ce0, "(port)X_I_2_ce0");
    sc_trace(mVcdFile, X_I_2_q0, "(port)X_I_2_q0");
    sc_trace(mVcdFile, Out_R_3_address0, "(port)Out_R_3_address0");
    sc_trace(mVcdFile, Out_R_3_ce0, "(port)Out_R_3_ce0");
    sc_trace(mVcdFile, Out_R_3_we0, "(port)Out_R_3_we0");
    sc_trace(mVcdFile, Out_R_3_d0, "(port)Out_R_3_d0");
    sc_trace(mVcdFile, Out_R_3_address1, "(port)Out_R_3_address1");
    sc_trace(mVcdFile, Out_R_3_ce1, "(port)Out_R_3_ce1");
    sc_trace(mVcdFile, Out_R_3_we1, "(port)Out_R_3_we1");
    sc_trace(mVcdFile, Out_R_3_d1, "(port)Out_R_3_d1");
    sc_trace(mVcdFile, Out_I_3_address0, "(port)Out_I_3_address0");
    sc_trace(mVcdFile, Out_I_3_ce0, "(port)Out_I_3_ce0");
    sc_trace(mVcdFile, Out_I_3_we0, "(port)Out_I_3_we0");
    sc_trace(mVcdFile, Out_I_3_d0, "(port)Out_I_3_d0");
    sc_trace(mVcdFile, Out_I_3_address1, "(port)Out_I_3_address1");
    sc_trace(mVcdFile, Out_I_3_ce1, "(port)Out_I_3_ce1");
    sc_trace(mVcdFile, Out_I_3_we1, "(port)Out_I_3_we1");
    sc_trace(mVcdFile, Out_I_3_d1, "(port)Out_I_3_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_267, "reg_267");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, reg_274, "reg_274");
    sc_trace(mVcdFile, grp_fu_227_p2, "grp_fu_227_p2");
    sc_trace(mVcdFile, reg_282, "reg_282");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, grp_fu_233_p2, "grp_fu_233_p2");
    sc_trace(mVcdFile, reg_289, "reg_289");
    sc_trace(mVcdFile, zext_ln39_fu_296_p1, "zext_ln39_fu_296_p1");
    sc_trace(mVcdFile, zext_ln39_reg_352, "zext_ln39_reg_352");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, j_fu_306_p2, "j_fu_306_p2");
    sc_trace(mVcdFile, j_reg_360, "j_reg_360");
    sc_trace(mVcdFile, grp_fu_263_p1, "grp_fu_263_p1");
    sc_trace(mVcdFile, x_assign_reg_365, "x_assign_reg_365");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_return, "grp_sin_or_cos_double_s_fu_189_ap_return");
    sc_trace(mVcdFile, tmp_i_i_reg_371, "tmp_i_i_reg_371");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_ready, "grp_sin_or_cos_double_s_fu_189_ap_ready");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_done, "grp_sin_or_cos_double_s_fu_189_ap_done");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_ready, "grp_sin_or_cos_double_s_fu_208_ap_ready");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_done, "grp_sin_or_cos_double_s_fu_208_ap_done");
    sc_trace(mVcdFile, ap_block_state5_on_subcall_done, "ap_block_state5_on_subcall_done");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_return, "grp_sin_or_cos_double_s_fu_208_ap_return");
    sc_trace(mVcdFile, tmp_i_i1_reg_376, "tmp_i_i1_reg_376");
    sc_trace(mVcdFile, a_reg_381, "a_reg_381");
    sc_trace(mVcdFile, grp_fu_257_p1, "grp_fu_257_p1");
    sc_trace(mVcdFile, c_reg_386, "c_reg_386");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_260_p1, "grp_fu_260_p1");
    sc_trace(mVcdFile, s_reg_392, "s_reg_392");
    sc_trace(mVcdFile, sext_ln48_fu_334_p1, "sext_ln48_fu_334_p1");
    sc_trace(mVcdFile, sext_ln48_reg_400, "sext_ln48_reg_400");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln46_fu_322_p2, "icmp_ln46_fu_322_p2");
    sc_trace(mVcdFile, grp_fu_245_p2, "grp_fu_245_p2");
    sc_trace(mVcdFile, tmp_7_reg_416, "tmp_7_reg_416");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_249_p2, "grp_fu_249_p2");
    sc_trace(mVcdFile, tmp_8_reg_421, "tmp_8_reg_421");
    sc_trace(mVcdFile, grp_fu_253_p2, "grp_fu_253_p2");
    sc_trace(mVcdFile, tmp_9_reg_427, "tmp_9_reg_427");
    sc_trace(mVcdFile, sext_ln50_fu_340_p1, "sext_ln50_fu_340_p1");
    sc_trace(mVcdFile, sext_ln50_reg_432, "sext_ln50_reg_432");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, i_10_fu_346_p2, "i_10_fu_346_p2");
    sc_trace(mVcdFile, i_10_reg_448, "i_10_reg_448");
    sc_trace(mVcdFile, grp_fu_237_p2, "grp_fu_237_p2");
    sc_trace(mVcdFile, tmp_6_reg_453, "tmp_6_reg_453");
    sc_trace(mVcdFile, grp_fu_241_p2, "grp_fu_241_p2");
    sc_trace(mVcdFile, tmp_4_reg_458, "tmp_4_reg_458");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_start, "grp_sin_or_cos_double_s_fu_189_ap_start");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_idle, "grp_sin_or_cos_double_s_fu_189_ap_idle");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_do_cos, "grp_sin_or_cos_double_s_fu_189_do_cos");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_start, "grp_sin_or_cos_double_s_fu_208_ap_start");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_idle, "grp_sin_or_cos_double_s_fu_208_ap_idle");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_do_cos, "grp_sin_or_cos_double_s_fu_208_do_cos");
    sc_trace(mVcdFile, a_0_reg_156, "a_0_reg_156");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_reg_168, "i_reg_168");
    sc_trace(mVcdFile, i_0_reg_179, "i_0_reg_179");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_189_ap_start_reg, "grp_sin_or_cos_double_s_fu_189_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_208_ap_start_reg, "grp_sin_or_cos_double_s_fu_208_ap_start_reg");
    sc_trace(mVcdFile, grp_fu_227_p0, "grp_fu_227_p0");
    sc_trace(mVcdFile, grp_fu_227_p1, "grp_fu_227_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_233_p0, "grp_fu_233_p0");
    sc_trace(mVcdFile, grp_fu_233_p1, "grp_fu_233_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_18_fu_312_p4, "tmp_18_fu_312_p4");
    sc_trace(mVcdFile, i_lower_fu_328_p2, "i_lower_fu_328_p2");
    sc_trace(mVcdFile, grp_fu_227_opcode, "grp_fu_227_opcode");
    sc_trace(mVcdFile, icmp_ln39_fu_300_p2, "icmp_ln39_fu_300_p2");
    sc_trace(mVcdFile, grp_fu_227_ce, "grp_fu_227_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_fu_233_opcode, "grp_fu_233_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fft_stage_179::~fft_stage_179() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_sin_or_cos_double_s_fu_189;
    delete grp_sin_or_cos_double_s_fu_208;
    delete fft_faddfsub_32nslbW_U62;
    delete fft_faddfsub_32nslbW_U63;
    delete fft_fadd_32ns_32nmb6_U64;
    delete fft_fadd_32ns_32nmb6_U65;
    delete fft_fmul_32ns_32nncg_U66;
    delete fft_fmul_32ns_32nncg_U67;
    delete fft_fmul_32ns_32nncg_U68;
    delete fft_fptrunc_64ns_ocq_U69;
    delete fft_fptrunc_64ns_ocq_U70;
    delete fft_fpext_32ns_64pcA_U71;
}

void fft_stage_179::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fft_stage_179::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_fu_322_p2.read(), ap_const_lv1_0))) {
        a_0_reg_156 = a_reg_381.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        a_0_reg_156 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln39_fu_300_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sin_or_cos_double_s_fu_189_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            grp_sin_or_cos_double_s_fu_189_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sin_or_cos_double_s_fu_189_ap_ready.read())) {
            grp_sin_or_cos_double_s_fu_189_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sin_or_cos_double_s_fu_208_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            grp_sin_or_cos_double_s_fu_208_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sin_or_cos_double_s_fu_208_ap_ready.read())) {
            grp_sin_or_cos_double_s_fu_208_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i_0_reg_179 = i_10_reg_448.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_0_reg_179 = zext_ln39_reg_352.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_fu_322_p2.read(), ap_const_lv1_0))) {
        i_reg_168 = j_reg_360.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_reg_168 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_block_state5_on_subcall_done.read(), ap_const_boolean_0))) {
        a_reg_381 = grp_fu_227_p2.read();
        tmp_i_i1_reg_376 = grp_sin_or_cos_double_s_fu_208_ap_return.read();
        tmp_i_i_reg_371 = grp_sin_or_cos_double_s_fu_189_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        c_reg_386 = grp_fu_257_p1.read();
        s_reg_392 = grp_fu_260_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_10_reg_448 = i_10_fu_346_p2.read();
        sext_ln50_reg_432 = sext_ln50_fu_340_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        j_reg_360 = j_fu_306_p2.read();
        zext_ln39_reg_352 = zext_ln39_fu_296_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        reg_267 = X_R_2_q0.read();
        reg_274 = X_I_2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        reg_282 = grp_fu_227_p2.read();
        reg_289 = grp_fu_233_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln46_fu_322_p2.read(), ap_const_lv1_1))) {
        sext_ln48_reg_400 = sext_ln48_fu_334_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        tmp_4_reg_458 = grp_fu_241_p2.read();
        tmp_6_reg_453 = grp_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_7_reg_416 = grp_fu_245_p2.read();
        tmp_8_reg_421 = grp_fu_249_p2.read();
        tmp_9_reg_427 = grp_fu_253_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_assign_reg_365 = grp_fu_263_p1.read();
    }
}

void fft_stage_179::thread_Out_I_3_address0() {
    Out_I_3_address0 =  (sc_lv<10>) (sext_ln48_reg_400.read());
}

void fft_stage_179::thread_Out_I_3_address1() {
    Out_I_3_address1 =  (sc_lv<10>) (sext_ln50_reg_432.read());
}

void fft_stage_179::thread_Out_I_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_I_3_ce0 = ap_const_logic_1;
    } else {
        Out_I_3_ce0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_I_3_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_I_3_ce1 = ap_const_logic_1;
    } else {
        Out_I_3_ce1 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_I_3_d0() {
    Out_I_3_d0 = reg_289.read();
}

void fft_stage_179::thread_Out_I_3_d1() {
    Out_I_3_d1 = tmp_4_reg_458.read();
}

void fft_stage_179::thread_Out_I_3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_I_3_we0 = ap_const_logic_1;
    } else {
        Out_I_3_we0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_I_3_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_I_3_we1 = ap_const_logic_1;
    } else {
        Out_I_3_we1 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_R_3_address0() {
    Out_R_3_address0 =  (sc_lv<10>) (sext_ln48_reg_400.read());
}

void fft_stage_179::thread_Out_R_3_address1() {
    Out_R_3_address1 =  (sc_lv<10>) (sext_ln50_reg_432.read());
}

void fft_stage_179::thread_Out_R_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_R_3_ce0 = ap_const_logic_1;
    } else {
        Out_R_3_ce0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_R_3_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_R_3_ce1 = ap_const_logic_1;
    } else {
        Out_R_3_ce1 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_R_3_d0() {
    Out_R_3_d0 = reg_282.read();
}

void fft_stage_179::thread_Out_R_3_d1() {
    Out_R_3_d1 = tmp_6_reg_453.read();
}

void fft_stage_179::thread_Out_R_3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_R_3_we0 = ap_const_logic_1;
    } else {
        Out_R_3_we0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_Out_R_3_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        Out_R_3_we1 = ap_const_logic_1;
    } else {
        Out_R_3_we1 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_X_I_2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        X_I_2_address0 =  (sc_lv<10>) (sext_ln50_fu_340_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        X_I_2_address0 =  (sc_lv<10>) (sext_ln48_fu_334_p1.read());
    } else {
        X_I_2_address0 = "XXXXXXXXXX";
    }
}

void fft_stage_179::thread_X_I_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        X_I_2_ce0 = ap_const_logic_1;
    } else {
        X_I_2_ce0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_X_R_2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        X_R_2_address0 =  (sc_lv<10>) (sext_ln50_fu_340_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        X_R_2_address0 =  (sc_lv<10>) (sext_ln48_fu_334_p1.read());
    } else {
        X_R_2_address0 = "XXXXXXXXXX";
    }
}

void fft_stage_179::thread_X_R_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        X_R_2_ce0 = ap_const_logic_1;
    } else {
        X_R_2_ce0 = ap_const_logic_0;
    }
}

void fft_stage_179::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fft_stage_179::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void fft_stage_179::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void fft_stage_179::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fft_stage_179::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void fft_stage_179::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void fft_stage_179::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void fft_stage_179::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void fft_stage_179::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fft_stage_179::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void fft_stage_179::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void fft_stage_179::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fft_stage_179::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fft_stage_179::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fft_stage_179::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fft_stage_179::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fft_stage_179::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fft_stage_179::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fft_stage_179::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fft_stage_179::thread_ap_block_state5_on_subcall_done() {
    ap_block_state5_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_sin_or_cos_double_s_fu_189_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_sin_or_cos_double_s_fu_208_ap_done.read()));
}

void fft_stage_179::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln39_fu_300_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fft_stage_179::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fft_stage_179::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln39_fu_300_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fft_stage_179::thread_grp_fu_227_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_on_subcall_done.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        grp_fu_227_ce = ap_const_logic_0;
    } else {
        grp_fu_227_ce = ap_const_logic_1;
    }
}

void fft_stage_179::thread_grp_fu_227_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        grp_fu_227_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_300_p2.read()))) {
        grp_fu_227_opcode = ap_const_lv2_0;
    } else {
        grp_fu_227_opcode =  (sc_lv<2>) ("XX");
    }
}

void fft_stage_179::thread_grp_fu_227_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_227_p0 = reg_267.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_227_p0 = tmp_7_reg_416.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_227_p0 = a_0_reg_156.read();
    } else {
        grp_fu_227_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_stage_179::thread_grp_fu_227_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_227_p1 = reg_282.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_227_p1 = tmp_8_reg_421.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_227_p1 = ap_const_lv32_BF490FDB;
    } else {
        grp_fu_227_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_stage_179::thread_grp_fu_233_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_233_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_233_opcode = ap_const_lv2_0;
    } else {
        grp_fu_233_opcode =  (sc_lv<2>) ("XX");
    }
}

void fft_stage_179::thread_grp_fu_233_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_233_p0 = reg_274.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_233_p0 = tmp_9_reg_427.read();
    } else {
        grp_fu_233_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_stage_179::thread_grp_fu_233_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_233_p1 = reg_289.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_233_p1 = tmp_8_reg_421.read();
    } else {
        grp_fu_233_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_stage_179::thread_grp_sin_or_cos_double_s_fu_189_ap_start() {
    grp_sin_or_cos_double_s_fu_189_ap_start = grp_sin_or_cos_double_s_fu_189_ap_start_reg.read();
}

void fft_stage_179::thread_grp_sin_or_cos_double_s_fu_189_do_cos() {
    grp_sin_or_cos_double_s_fu_189_do_cos =  (sc_logic) (ap_const_lv1_1[0]);
}

void fft_stage_179::thread_grp_sin_or_cos_double_s_fu_208_ap_start() {
    grp_sin_or_cos_double_s_fu_208_ap_start = grp_sin_or_cos_double_s_fu_208_ap_start_reg.read();
}

void fft_stage_179::thread_grp_sin_or_cos_double_s_fu_208_do_cos() {
    grp_sin_or_cos_double_s_fu_208_do_cos =  (sc_logic) (ap_const_lv1_0[0]);
}

void fft_stage_179::thread_i_10_fu_346_p2() {
    i_10_fu_346_p2 = (!i_0_reg_179.read().is_01() || !ap_const_lv32_8.is_01())? sc_lv<32>(): (sc_bigint<32>(i_0_reg_179.read()) + sc_biguint<32>(ap_const_lv32_8));
}

void fft_stage_179::thread_i_lower_fu_328_p2() {
    i_lower_fu_328_p2 = (!i_0_reg_179.read().is_01() || !ap_const_lv32_4.is_01())? sc_lv<32>(): (sc_bigint<32>(i_0_reg_179.read()) + sc_biguint<32>(ap_const_lv32_4));
}

void fft_stage_179::thread_icmp_ln39_fu_300_p2() {
    icmp_ln39_fu_300_p2 = (!i_reg_168.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_168.read() == ap_const_lv3_4);
}

void fft_stage_179::thread_icmp_ln46_fu_322_p2() {
    icmp_ln46_fu_322_p2 = (!tmp_18_fu_312_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<1>(): (sc_bigint<22>(tmp_18_fu_312_p4.read()) < sc_bigint<22>(ap_const_lv22_1));
}

void fft_stage_179::thread_j_fu_306_p2() {
    j_fu_306_p2 = (!i_reg_168.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_168.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void fft_stage_179::thread_sext_ln48_fu_334_p1() {
    sext_ln48_fu_334_p1 = esl_sext<64,32>(i_lower_fu_328_p2.read());
}

void fft_stage_179::thread_sext_ln50_fu_340_p1() {
    sext_ln50_fu_340_p1 = esl_sext<64,32>(i_0_reg_179.read());
}

void fft_stage_179::thread_tmp_18_fu_312_p4() {
    tmp_18_fu_312_p4 = i_0_reg_179.read().range(31, 10);
}

void fft_stage_179::thread_zext_ln39_fu_296_p1() {
    zext_ln39_fu_296_p1 = esl_zext<32,3>(i_reg_168.read());
}

void fft_stage_179::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln39_fu_300_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_block_state5_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln46_fu_322_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

